/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef brokerSUBSCRIPTIONTABLE_DATA_SET_H
#define brokerSUBSCRIPTIONTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table brokerSubscriptionTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * QPID-MESSAGING-MIB::brokerSubscriptionTable is subid 1 of brokerSubscriptions.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18060.5672.1.1.9.1, length: 12
     */


    int            
        brokerSubscriptionTable_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionTable_undo_cleanup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionTable_undo(brokerSubscriptionTable_rowreq_ctx *
                                     rowreq_ctx);
    int            
        brokerSubscriptionTable_commit(brokerSubscriptionTable_rowreq_ctx *
                                       rowreq_ctx);
    int            
        brokerSubscriptionTable_undo_commit
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);


    int            
        brokerSubscriptionSessionRef_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         char *brokerSubscriptionSessionRef_val_ptr,
         size_t brokerSubscriptionSessionRef_val_ptr_len);
    int            
        brokerSubscriptionSessionRef_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionSessionRef_set(brokerSubscriptionTable_rowreq_ctx
                                         * rowreq_ctx,
                                         char
                                         *brokerSubscriptionSessionRef_val_ptr,
                                         size_t
                                         brokerSubscriptionSessionRef_val_ptr_len);
    int            
        brokerSubscriptionSessionRef_undo
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);

    int            
        brokerSubscriptionQueueRef_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         char *brokerSubscriptionQueueRef_val_ptr,
         size_t brokerSubscriptionQueueRef_val_ptr_len);
    int            
        brokerSubscriptionQueueRef_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionQueueRef_set(brokerSubscriptionTable_rowreq_ctx *
                                       rowreq_ctx,
                                       char
                                       *brokerSubscriptionQueueRef_val_ptr,
                                       size_t
                                       brokerSubscriptionQueueRef_val_ptr_len);
    int            
        brokerSubscriptionQueueRef_undo(brokerSubscriptionTable_rowreq_ctx
                                        * rowreq_ctx);

    int            
        brokerSubscriptionName_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         char *brokerSubscriptionName_val_ptr,
         size_t brokerSubscriptionName_val_ptr_len);
    int            
        brokerSubscriptionName_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionName_set(brokerSubscriptionTable_rowreq_ctx *
                                   rowreq_ctx,
                                   char *brokerSubscriptionName_val_ptr,
                                   size_t
                                   brokerSubscriptionName_val_ptr_len);
    int            
        brokerSubscriptionName_undo(brokerSubscriptionTable_rowreq_ctx *
                                    rowreq_ctx);

    int            
        brokerSubscriptionBrowsing_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         u_long brokerSubscriptionBrowsing_val);
    int            
        brokerSubscriptionBrowsing_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionBrowsing_set(brokerSubscriptionTable_rowreq_ctx *
                                       rowreq_ctx,
                                       u_long
                                       brokerSubscriptionBrowsing_val);
    int            
        brokerSubscriptionBrowsing_undo(brokerSubscriptionTable_rowreq_ctx
                                        * rowreq_ctx);

    int            
        brokerSubscriptionAcknowledged_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         u_long brokerSubscriptionAcknowledged_val);
    int            
        brokerSubscriptionAcknowledged_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionAcknowledged_set
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         u_long brokerSubscriptionAcknowledged_val);
    int            
        brokerSubscriptionAcknowledged_undo
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);

    int            
        brokerSubscriptionExclusive_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         u_long brokerSubscriptionExclusive_val);
    int            
        brokerSubscriptionExclusive_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionExclusive_set(brokerSubscriptionTable_rowreq_ctx
                                        * rowreq_ctx,
                                        u_long
                                        brokerSubscriptionExclusive_val);
    int            
        brokerSubscriptionExclusive_undo(brokerSubscriptionTable_rowreq_ctx
                                         * rowreq_ctx);

    int            
        brokerSubscriptionCreditMode_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         char *brokerSubscriptionCreditMode_val_ptr,
         size_t brokerSubscriptionCreditMode_val_ptr_len);
    int            
        brokerSubscriptionCreditMode_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionCreditMode_set(brokerSubscriptionTable_rowreq_ctx
                                         * rowreq_ctx,
                                         char
                                         *brokerSubscriptionCreditMode_val_ptr,
                                         size_t
                                         brokerSubscriptionCreditMode_val_ptr_len);
    int            
        brokerSubscriptionCreditMode_undo
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);

    int            
        brokerSubscriptionArguments_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         char *brokerSubscriptionArguments_val_ptr,
         size_t brokerSubscriptionArguments_val_ptr_len);
    int            
        brokerSubscriptionArguments_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionArguments_set(brokerSubscriptionTable_rowreq_ctx
                                        * rowreq_ctx,
                                        char
                                        *brokerSubscriptionArguments_val_ptr,
                                        size_t
                                        brokerSubscriptionArguments_val_ptr_len);
    int            
        brokerSubscriptionArguments_undo(brokerSubscriptionTable_rowreq_ctx
                                         * rowreq_ctx);

    int            
        brokerSubscriptionDelivered_check_value
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx,
         U64 brokerSubscriptionDelivered_val);
    int            
        brokerSubscriptionDelivered_undo_setup
        (brokerSubscriptionTable_rowreq_ctx * rowreq_ctx);
    int            
        brokerSubscriptionDelivered_set(brokerSubscriptionTable_rowreq_ctx
                                        * rowreq_ctx,
                                        U64
                                        brokerSubscriptionDelivered_val);
    int            
        brokerSubscriptionDelivered_undo(brokerSubscriptionTable_rowreq_ctx
                                         * rowreq_ctx);


    int            
        brokerSubscriptionTable_check_dependencies
        (brokerSubscriptionTable_rowreq_ctx * ctx);


#ifdef __cplusplus
}
#endif
#endif                          /* brokerSUBSCRIPTIONTABLE_DATA_SET_H */
