/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file qpid010LinkTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef qpid010LINKTABLE_DATA_GET_H
#define qpid010LINKTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table qpid010LinkTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * MRG-MESSAGING-MIB::qpid010LinkTable is subid 1 of qpid010Links.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18060,15.1.1.11.1, length: 12
     */
    /*
     * indexes
     */

    int             qpid010LinkVhostRef_get(qpid010LinkTable_rowreq_ctx *
                                           rowreq_ctx,
                                           char
                                           **qpid010LinkVhostRef_val_ptr_ptr,
                                           size_t
                                           *qpid010LinkVhostRef_val_ptr_len_ptr);
    int             qpid010LinkHost_get(qpid010LinkTable_rowreq_ctx *
                                       rowreq_ctx,
                                       char **qpid010LinkHost_val_ptr_ptr,
                                       size_t
                                       *qpid010LinkHost_val_ptr_len_ptr);
    int             qpid010LinkPort_get(qpid010LinkTable_rowreq_ctx *
                                       rowreq_ctx,
                                       long *qpid010LinkPort_val_ptr);
    int             qpid010LinkTransport_get(qpid010LinkTable_rowreq_ctx *
                                            rowreq_ctx,
                                            char
                                            **qpid010LinkTransport_val_ptr_ptr,
                                            size_t
                                            *qpid010LinkTransport_val_ptr_len_ptr);
    int             qpid010LinkDurable_get(qpid010LinkTable_rowreq_ctx *
                                          rowreq_ctx,
                                          u_long *
                                          qpid010LinkDurable_val_ptr);
    int             qpid010LinkState_get(qpid010LinkTable_rowreq_ctx *
                                        rowreq_ctx,
                                        char **qpid010LinkState_val_ptr_ptr,
                                        size_t
                                        *qpid010LinkState_val_ptr_len_ptr);
    int             qpid010LinkLastError_get(qpid010LinkTable_rowreq_ctx *
                                            rowreq_ctx,
                                            char
                                            **qpid010LinkLastError_val_ptr_ptr,
                                            size_t
                                            *qpid010LinkLastError_val_ptr_len_ptr);


    int            
        qpid010LinkTable_indexes_set_tbl_idx(qpid010LinkTable_mib_index *
                                            tbl_idx,
                                            u_long
                                            qpid010LinkInternalIndex_val);
    int             qpid010LinkTable_indexes_set(qpid010LinkTable_rowreq_ctx
                                                * rowreq_ctx,
                                                u_long
                                                qpid010LinkInternalIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* qpid010LINKTABLE_DATA_GET_H */
/** @} */
