/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "LinkTable.h"


#include "LinkTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table qpid010LinkTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MRG-MESSAGING-MIB::qpid010LinkTable is subid 1 of qpid010Links.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.18060.5672.1.1.11.1, length: 12
 */

/**
 * initialization for qpid010LinkTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param qpid010LinkTable_reg
 *        Pointer to qpid010LinkTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
qpid010LinkTable_init_data(qpid010LinkTable_registration *
                           qpid010LinkTable_reg)
{
    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkTable_init_data",
                "called\n"));

    /*
     * TODO:303:o: Initialize qpid010LinkTable data.
     */
    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/

    return MFD_SUCCESS;
}                               /* qpid010LinkTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
qpid010LinkTable_container_init(netsnmp_container ** container_ptr_ptr,
                                netsnmp_cache * cache)
{
    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkTable_container_init",
                "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to qpid010LinkTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,
                 "bad cache param to qpid010LinkTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up qpid010LinkTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = QPID010LINKTABLE_CACHE_TIMEOUT;    /* seconds */
}                               /* qpid010LinkTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before qpid010LinkTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
qpid010LinkTable_container_shutdown(netsnmp_container * container_ptr)
{
    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkTable_container_shutdown", "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,
                 "bad params to qpid010LinkTable_container_shutdown\n");
        return;
    }

}                               /* qpid010LinkTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement qpid010LinkTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  qpid010LinkTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
qpid010LinkTable_container_load(netsnmp_container * container)
{
    qpid010LinkTable_rowreq_ctx *rowreq_ctx;

    /*
     * temporary storage for index values
     */
    /*
     * qpid010LinkInternalIndex(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/r/d/h
     */
    u_long          qpid010LinkInternalIndex;
    qpid010LinkTable_data qmfData;



    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkTable_container_load",
                "called\n"));

    /*
     * Load/update data in the qpid010LinkTable container.
     * loop over your qpid010LinkTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    uint64_t u64Data;

    void *pEvent = qpidGet("link");

    int index;
    uint objects;
    objects = qpidGetCount(pEvent);

    qpid010LinkInternalIndex = 0;
    for (index = 0; index < objects; ++index) {

    	void * pRow = qpidGetDataRow(pEvent, index);
    	if (!pRow)
    		continue;

        strncpy(qmfData.qpid010LinkVhostRef,
        		qpidGetString(pRow, "vhostRef"), 254);
        qmfData.qpid010LinkVhostRef_len = strlen(qmfData.qpid010LinkVhostRef) + 1;

        strncpy(qmfData.qpid010LinkName,
        		qpidGetString(pRow, "name"), 254);
        qmfData.qpid010LinkName_len = strlen(qmfData.qpid010LinkName) + 1;

        strncpy(qmfData.qpid010LinkHost,
        		qpidGetString(pRow, "host"), 254);
        qmfData.qpid010LinkHost_len = strlen(qmfData.qpid010LinkHost) + 1;

        strncpy(qmfData.qpid010LinkTransport,
        		qpidGetString(pRow, "transport"), 254);
        qmfData.qpid010LinkTransport_len = strlen(qmfData.qpid010LinkTransport) + 1;

        strncpy(qmfData.qpid010LinkConnectionRef,
        		qpidGetString(pRow, "connectionRef"), 254);
        qmfData.qpid010LinkConnectionRef_len = strlen(qmfData.qpid010LinkConnectionRef) + 1;

        strncpy(qmfData.qpid010LinkState,
        		qpidGetString(pRow, "linkState"), 254);
        qmfData.qpid010LinkState_len = strlen(qmfData.qpid010LinkState) + 1;

        strncpy(qmfData.qpid010LinkLastError,
        		qpidGetString(pRow, "lastError"), 65534);
        qmfData.qpid010LinkLastError_len = strlen(qmfData.qpid010LinkLastError) + 1;

        qmfData.qpid010LinkDurable = qpidGetBool(pRow, "durable");
        qmfData.qpid010LinkPort = qpidGetU32(pRow, "linkPort");

        /*
         * set indexes in new qpid010LinkTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = qpid010LinkTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if (MFD_SUCCESS !=
            qpid010LinkTable_indexes_set(rowreq_ctx,
                                         qpid010LinkInternalIndex)) {
            snmp_log(LOG_ERR,
                     "error setting index while loading "
                     "qpid010LinkTable data.\n");
            qpid010LinkTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }
        ++qpid010LinkInternalIndex;

        /*
         * setup/save data for qpid010LinkVhostRef
         * qpid010LinkVhostRef(1)/ObjId/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for qpid010LinkVhostRef data
         */
        if ((NULL == rowreq_ctx->data.qpid010LinkVhostRef) ||
            (rowreq_ctx->data.qpid010LinkVhostRef_len <
             (qmfData.qpid010LinkVhostRef_len * sizeof(qmfData.qpid010LinkVhostRef[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (qpid010LinkVhostRef)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.qpid010LinkVhostRef_len =
            qmfData.qpid010LinkVhostRef_len * sizeof(qmfData.qpid010LinkVhostRef[0]);
        memcpy(rowreq_ctx->data.qpid010LinkVhostRef, qmfData.qpid010LinkVhostRef,
        		qmfData.qpid010LinkVhostRef_len * sizeof(qmfData.qpid010LinkVhostRef[0]));

        /*
         * setup/save data for qpid010LinkName
         * qpid010LinkName(2)/Sstr/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for qpid010LinkName data
         */
        if ((NULL == rowreq_ctx->data.qpid010LinkName) ||
            (rowreq_ctx->data.qpid010LinkName_len <
             (qmfData.qpid010LinkName_len * sizeof(qmfData.qpid010LinkName[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (qpid010LinkName)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.qpid010LinkName_len =
        		qmfData.qpid010LinkName_len * sizeof(qmfData.qpid010LinkName[0]);
        memcpy(rowreq_ctx->data.qpid010LinkName, qmfData.qpid010LinkName,
        		qmfData.qpid010LinkName_len * sizeof(qmfData.qpid010LinkName[0]));

        /*
         * setup/save data for qpid010LinkHost
         * qpid010LinkHost(3)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for qpid010LinkHost data
         */
        if ((NULL == rowreq_ctx->data.qpid010LinkHost) ||
            (rowreq_ctx->data.qpid010LinkHost_len <
             (qmfData.qpid010LinkHost_len * sizeof(qmfData.qpid010LinkHost[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (qpid010LinkHost)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.qpid010LinkHost_len =
        		qmfData.qpid010LinkHost_len * sizeof(qmfData.qpid010LinkHost[0]);
        memcpy(rowreq_ctx->data.qpid010LinkHost, qmfData.qpid010LinkHost,
        		qmfData.qpid010LinkHost_len * sizeof(qmfData.qpid010LinkHost[0]));

        /*
         * setup/save data for qpid010LinkPort
         * qpid010LinkPort(4)/Uint16/ASN_INTEGER/long(long)//l/A/w/e/r/d/H
         */
    /** no mapping */
        rowreq_ctx->data.qpid010LinkPort = qmfData.qpid010LinkPort;

        /*
         * setup/save data for qpid010LinkTransport
         * qpid010LinkTransport(5)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for qpid010LinkTransport data
         */
        if ((NULL == rowreq_ctx->data.qpid010LinkTransport) ||
            (rowreq_ctx->data.qpid010LinkTransport_len <
             (qmfData.qpid010LinkTransport_len *
              sizeof(qmfData.qpid010LinkTransport[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (qpid010LinkTransport)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.qpid010LinkTransport_len =
        		qmfData.qpid010LinkTransport_len * sizeof(qmfData.qpid010LinkTransport[0]);
        memcpy(rowreq_ctx->data.qpid010LinkTransport, qmfData.qpid010LinkTransport,
        		qmfData.qpid010LinkTransport_len * sizeof(qmfData.qpid010LinkTransport[0]));

        /*
         * setup/save data for qpid010LinkDurable
         * qpid010LinkDurable(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */

        if (qmfData.qpid010LinkDurable == 0)
        	qmfData.qpid010LinkDurable = TRUTHVALUE_FALSE;
        rowreq_ctx->data.qpid010LinkDurable = qmfData.qpid010LinkDurable;

        /*
         * setup/save data for qpid010LinkConnectionRef
         * qpid010LinkConnectionRef(7)/ObjId/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for qpid010LinkConnectionRef data
         */
        if ((NULL == rowreq_ctx->data.qpid010LinkConnectionRef) ||
            (rowreq_ctx->data.qpid010LinkConnectionRef_len <
             (qmfData.qpid010LinkConnectionRef_len *
              sizeof(qmfData.qpid010LinkConnectionRef[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (qpid010LinkConnectionRef)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.qpid010LinkConnectionRef_len =
        		qmfData.qpid010LinkConnectionRef_len *
            sizeof(qmfData.qpid010LinkConnectionRef[0]);
        memcpy(rowreq_ctx->data.qpid010LinkConnectionRef,
        		qmfData.qpid010LinkConnectionRef,
        		qmfData.qpid010LinkConnectionRef_len *
               sizeof(qmfData.qpid010LinkConnectionRef[0]));

        /*
         * setup/save data for qpid010LinkState
         * qpid010LinkState(8)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for qpid010LinkState data
         */
        if ((NULL == rowreq_ctx->data.qpid010LinkState) ||
            (rowreq_ctx->data.qpid010LinkState_len <
             (qmfData.qpid010LinkState_len * sizeof(qmfData.qpid010LinkState[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (qpid010LinkState)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.qpid010LinkState_len =
        		qmfData.qpid010LinkState_len * sizeof(qmfData.qpid010LinkState[0]);
        memcpy(rowreq_ctx->data.qpid010LinkState, qmfData.qpid010LinkState,
        		qmfData.qpid010LinkState_len * sizeof(qmfData.qpid010LinkState[0]));

        /*
         * setup/save data for qpid010LinkLastError
         * qpid010LinkLastError(9)/Lstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for qpid010LinkLastError data
         */
        if ((NULL == rowreq_ctx->data.qpid010LinkLastError) ||
            (rowreq_ctx->data.qpid010LinkLastError_len <
             (qmfData.qpid010LinkLastError_len *
              sizeof(qmfData.qpid010LinkLastError[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (qpid010LinkLastError)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.qpid010LinkLastError_len =
        		qmfData.qpid010LinkLastError_len * sizeof(qmfData.qpid010LinkLastError[0]);
        memcpy(rowreq_ctx->data.qpid010LinkLastError, qmfData.qpid010LinkLastError,
        		qmfData.qpid010LinkLastError_len * sizeof(qmfData.qpid010LinkLastError[0]));


        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        qpidReleaseDataRow(pRow);
    }

    qpidRelease(pEvent);

    DEBUGMSGT(("verbose:qpid010LinkTable:qpid010LinkTable_container_load",
               "inserted %d records\n", qpid010LinkInternalIndex));

    return MFD_SUCCESS;
}                               /* qpid010LinkTable_container_load */


/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
qpid010LinkTable_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkTable_container_free",
                "called\n"));

    /*
     * TODO:380:M: Free qpid010LinkTable container data.
     */
}                               /* qpid010LinkTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
qpid010LinkTable_row_prep(qpid010LinkTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkTable_row_prep",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
}                               /* qpid010LinkTable_row_prep */

/*
 * TODO:420:r: Implement qpid010LinkTable index validation.
 */
/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::qpid010LinkEntry.qpid010LinkInternalIndex
 * qpid010LinkInternalIndex is subid 10 of qpid010LinkEntry.
 * Its status is Current, and its access level is NoAccess.
 * OID: .1.3.6.1.4.1.18060.5672.1.1.11.1.1.10
 * Description:
Internal index for link table
 *
 * Attributes:
 *   accessible 0     isscalar 0     enums  0      hasdefval 0
 *   readable   0     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 *
 *
 *
 * NOTE: NODE qpid010LinkInternalIndex IS NOT ACCESSIBLE
 *
 *
 */
/**
 * check validity of qpid010LinkInternalIndex index portion
 *
 * @retval MFD_SUCCESS   : the incoming value is legal
 * @retval MFD_ERROR     : the incoming value is NOT legal
 *
 * @note this is not the place to do any checks for the sanity
 *       of multiple indexes. Those types of checks should be done in the
 *       qpid010LinkTable_validate_index() function.
 *
 * @note Also keep in mind that if the index refers to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 * The following checks have already been done for you:
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 */
int
qpid010LinkInternalIndex_check_index(qpid010LinkTable_rowreq_ctx *
                                     rowreq_ctx)
{
    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkInternalIndex_check_index", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:426:M: |-> Check qpid010LinkTable index qpid010LinkInternalIndex.
     * check that index value in the table context is legal.
     * (rowreq_ctx->tbl_index.qpid010LinkInternalIndex)
     */

    return MFD_SUCCESS;         /* qpid010LinkInternalIndex index ok */
}                               /* qpid010LinkInternalIndex_check_index */

/**
 * verify specified index is valid.
 *
 * This check is independent of whether or not the values specified for
 * the columns of the new row are valid. Column values and row consistency
 * will be checked later. At this point, only the index values should be
 * checked.
 *
 * All of the individual index validation functions have been called, so this
 * is the place to make sure they are valid as a whole when combined. If
 * you only have one index, then you probably don't need to do anything else
 * here.
 * 
 * @note Keep in mind that if the indexes refer to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 *
 * @param qpid010LinkTable_reg
 *        Pointer to the user registration data
 * @param qpid010LinkTable_rowreq_ctx
 *        Pointer to the users context.
 * @retval MFD_SUCCESS            : success
 * @retval MFD_CANNOT_CREATE_NOW  : index not valid right now
 * @retval MFD_CANNOT_CREATE_EVER : index never valid
 */
int
qpid010LinkTable_validate_index(qpid010LinkTable_registration *
                                qpid010LinkTable_reg,
                                qpid010LinkTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:qpid010LinkTable:qpid010LinkTable_validate_index",
                "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:430:M: |-> Validate potential qpid010LinkTable index.
     */
    if (1) {
        snmp_log(LOG_WARNING, "invalid index for a new row in the "
                 "qpid010LinkTable table.\n");
        /*
         * determine failure type.
         *
         * If the index could not ever be created, return MFD_NOT_EVER
         * If the index can not be created under the present circumstances
         * (even though it could be created under other circumstances),
         * return MFD_NOT_NOW.
         */
        if (0) {
            return MFD_CANNOT_CREATE_EVER;
        } else {
            return MFD_CANNOT_CREATE_NOW;
        }
    }

    return rc;
}                               /* qpid010LinkTable_validate_index */

/** @} */
