/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef brokerLINKTABLE_H
#define brokerLINKTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

    /*
     * other required module components 
     */
    /* *INDENT-OFF*  */
config_add_mib(QPID-MESSAGING-MIB)
config_require(QPID-MESSAGING-MIB/brokerLinkTable/brokerLinkTable_interface)
config_require(QPID-MESSAGING-MIB/brokerLinkTable/brokerLinkTable_data_access)
config_require(QPID-MESSAGING-MIB/brokerLinkTable/brokerLinkTable_data_get)
config_require(QPID-MESSAGING-MIB/brokerLinkTable/brokerLinkTable_data_set)
    /* *INDENT-ON*  */

    /*
     * OID and column number definitions for brokerLinkTable 
     */
#include "LinkTable_oids.h"

    /*
     * enum definions 
     */
#include "../enums.h"

    /*
     *********************************************************************
     * function declarations
     */
    void            init_LinkTable(void);
    void            shutdown_brokerLinkTable(void);

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table brokerLinkTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * QPID-MESSAGING-MIB::brokerLinkTable is subid 1 of brokerLinks.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18060.5672.1.1.11.1, length: 12
     */
    /*
     *********************************************************************
     * When you register your mib, you get to provide a generic
     * pointer that will be passed back to you for most of the
     * functions calls.
     *
     * TODO:100:r: Review all context structures
     */
    /*
     * TODO:101:o: |-> Review brokerLinkTable registration context.
     */
    typedef netsnmp_data_list brokerLinkTable_registration;

/**********************************************************************/
    /*
     * TODO:110:r: |-> Review brokerLinkTable data context structure.
     * This structure is used to represent the data for brokerLinkTable.
     */
    /*
     * This structure contains storage for all the columns defined in the
     * brokerLinkTable.
     */
    typedef struct brokerLinkTable_data_s {

        /*
         * brokerLinkVhostRef(1)/ObjId/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
        char            brokerLinkVhostRef[255];
        size_t          brokerLinkVhostRef_len;        /* # of char elements, not bytes */

        /*
         * brokerLinkName(2)/Sstr/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
        char            brokerLinkName[255];
        size_t          brokerLinkName_len;    /* # of char elements, not bytes */

        /*
         * brokerLinkHost(3)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        char            brokerLinkHost[255];
        size_t          brokerLinkHost_len;    /* # of char elements, not bytes */

        /*
         * brokerLinkPort(4)/Uint16/ASN_INTEGER/long(long)//l/A/w/e/r/d/H
         */
        long            brokerLinkPort;

        /*
         * brokerLinkTransport(5)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        char            brokerLinkTransport[255];
        size_t          brokerLinkTransport_len;       /* # of char elements, not bytes */

        /*
         * brokerLinkDurable(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
        u_long          brokerLinkDurable;

        /*
         * brokerLinkConnectionRef(7)/ObjId/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        char            brokerLinkConnectionRef[255];
        size_t          brokerLinkConnectionRef_len;   /* # of char elements, not bytes */

        /*
         * brokerLinkState(8)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        char            brokerLinkState[255];
        size_t          brokerLinkState_len;   /* # of char elements, not bytes */

        /*
         * brokerLinkLastError(9)/Lstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        char            brokerLinkLastError[65535];
        size_t          brokerLinkLastError_len;       /* # of char elements, not bytes */

    } brokerLinkTable_data;


    /*
     *********************************************************************
     * TODO:115:o: |-> Review brokerLinkTable undo context.
     * We're just going to use the same data structure for our
     * undo_context. If you want to do something more efficent,
     * define your typedef here.
     */
    typedef brokerLinkTable_data brokerLinkTable_undo_data;

    /*
     * TODO:120:r: |-> Review brokerLinkTable mib index.
     * This structure is used to represent the index for brokerLinkTable.
     */
    typedef struct brokerLinkTable_mib_index_s {

        /*
         * brokerLinkInternalIndex(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/r/d/h
         */
        u_long          brokerLinkInternalIndex;


    } brokerLinkTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review brokerLinkTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     */
#define MAX_brokerLinkTable_IDX_LEN     1


    /*
     *********************************************************************
     * TODO:130:o: |-> Review brokerLinkTable Row request (rowreq) context.
     * When your functions are called, you will be passed a
     * brokerLinkTable_rowreq_ctx pointer.
     */
    typedef struct brokerLinkTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
        netsnmp_index   oid_idx;
        oid             oid_tmp[MAX_brokerLinkTable_IDX_LEN];

        brokerLinkTable_mib_index tbl_idx;

        brokerLinkTable_data data;
        brokerLinkTable_undo_data *undo;
        unsigned int    column_set_flags;       /* flags for set columns */


        /*
         * flags per row. Currently, the first (lower) 8 bits are reserved
         * for the user. See mfd.h for other flags.
         */
        u_int           rowreq_flags;

        /*
         * TODO:131:o: |   |-> Add useful data to brokerLinkTable rowreq context.
         */

        /*
         * storage for future expansion
         */
        netsnmp_data_list *brokerLinkTable_data_list;

    } brokerLinkTable_rowreq_ctx;

    typedef struct brokerLinkTable_ref_rowreq_ctx_s {
        brokerLinkTable_rowreq_ctx *rowreq_ctx;
    } brokerLinkTable_ref_rowreq_ctx;

    /*
     *********************************************************************
     * function prototypes
     */
    int            
        brokerLinkTable_pre_request(brokerLinkTable_registration *
                                     user_context);
    int            
        brokerLinkTable_post_request(brokerLinkTable_registration *
                                      user_context, int rc);

    int            
        brokerLinkTable_rowreq_ctx_init(brokerLinkTable_rowreq_ctx *
                                         rowreq_ctx, void *user_init_ctx);
    void           
        brokerLinkTable_rowreq_ctx_cleanup(brokerLinkTable_rowreq_ctx *
                                            rowreq_ctx);

    int            
        brokerLinkTable_check_dependencies(brokerLinkTable_rowreq_ctx *
                                            rowreq_ctx);
    int             brokerLinkTable_commit(brokerLinkTable_rowreq_ctx *
                                            rowreq_ctx);

    brokerLinkTable_rowreq_ctx
        *brokerLinkTable_row_find_by_mib_index(brokerLinkTable_mib_index
                                                * mib_idx);

    extern const oid brokerLinkTable_oid[];
    extern const int brokerLinkTable_oid_size;


#include "LinkTable_interface.h"
#include "LinkTable_data_access.h"
#include "LinkTable_data_get.h"
#include "LinkTable_data_set.h"

    /*
     * DUMMY markers, ignore
     *
     * TODO:099:x: *************************************************************
     * TODO:199:x: *************************************************************
     * TODO:299:x: *************************************************************
     * TODO:399:x: *************************************************************
     * TODO:499:x: *************************************************************
     */

#ifdef __cplusplus
}
#endif
#endif                          /* brokerLINKTABLE_H */
/** @} */
