/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "rhm010QueueTable.h"


/** @defgroup data_set data_set: Routines to set data
 *
 * These routines are used to set the value for individual objects. The
 * row context is passed, along with the new value.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rhm010QueueTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MRG-MESSAGING-MIB::rhm010QueueTable is subid 1 of rhm010Queues.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.6.1, length: 12
 */
    /*
     * NOTE: if you update this chart, please update the versions in
     *       local/mib2c-conf.d/parent-set.m2i
     *       agent/mibgroup/helpers/baby_steps.c
     * while you're at it.
     */
    /*
     ***********************************************************************
     * Baby Steps Flow Chart (2004.06.05)                                  *
     *                                                                     *
     * +--------------+    +================+    U = unconditional path    *
     * |optional state|    ||required state||    S = path for success      *
     * +--------------+    +================+    E = path for error        *
     ***********************************************************************
     *
     *                        +--------------+
     *                        |     pre      |
     *                        |   request    |
     *                        +--------------+
     *                               | U
     *                        +==============+
     *       +----------------||  object    ||
     *       |              E ||  lookup    ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |              E ||   check    ||
     *       |<---------------||   values   ||
     *       |                +==============+
     *       |                       | S
     *       |                +==============+
     *       |       +<-------||   undo     ||
     *       |       |      E ||   setup    ||
     *       |       |        +==============+
     *       |       |               | S
     *       |       |        +==============+
     *       |       |        ||    set     ||-------------------------->+
     *       |       |        ||   value    || E                         |
     *       |       |        +==============+                           |
     *       |       |               | S                                 |
     *       |       |        +--------------+                           |
     *       |       |        |    check     |-------------------------->|
     *       |       |        |  consistency | E                         |
     *       |       |        +--------------+                           |
     *       |       |               | S                                 |
     *       |       |        +==============+         +==============+  |
     *       |       |        ||   commit   ||-------->||     undo   ||  |
     *       |       |        ||            || E       ||    commit  ||  |
     *       |       |        +==============+         +==============+  |
     *       |       |               | S                     U |<--------+
     *       |       |        +--------------+         +==============+
     *       |       |        | irreversible |         ||    undo    ||
     *       |       |        |    commit    |         ||     set    ||
     *       |       |        +--------------+         +==============+
     *       |       |               | U                     U |
     *       |       +-------------->|<------------------------+
     *       |                +==============+
     *       |                ||   undo     ||
     *       |                ||  cleanup   ||
     *       |                +==============+
     *       +---------------------->| U
     *                        +--------------+
     *                        |    post      |
     *                        |   request    |
     *                        +--------------+
     *
     */

/**
 * Setup up context with information needed to undo a set request.
 *
 * This function will be called before the individual node undo setup
 * functions are called. If you need to do any undo setup that is not
 * related to a specific column, you can do it here.
 *
 * Note that the undo context has been allocated with
 * rhm010QueueTable_allocate_data(), but may need extra
 * initialization similar to what you may have done in
 * rhm010QueueTable_rowreq_ctx_init().
 * Note that an individual node's undo_setup function will only be called
 * if that node is being set to a new value.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in the node's undo_setup
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
rhm010QueueTable_undo_setup(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueTable_undo_setup",
                "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:451:M: |-> Setup rhm010QueueTable undo.
     * set up rhm010QueueTable undo information, in preparation for a set.
     * Undo storage is in (* rhm010QueueFlowStoppedCount_val_ptr )*
     */

    return rc;
}                               /* rhm010QueueTable_undo_setup */

/**
 * Undo a set request.
 *
 * This function will be called before the individual node undo
 * functions are called. If you need to do any undo that is not
 * related to a specific column, you can do it here.
 *
 * Note that an individual node's undo function will only be called
 * if that node is being set to a new value.
 *
 * If there is anything  specific to a particular column (e.g. releasing
 * memory for a string), you should do that setup in the node's undo
 * function, so it won't be done unless it is necessary.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 */
int
rhm010QueueTable_undo(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueTable_undo",
                "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:451:M: |-> rhm010QueueTable undo.
     * rhm010QueueTable undo information, in response to a failed set.
     * Undo storage is in (* rhm010QueueFlowStoppedCount_val_ptr )*
     */

    return rc;
}                               /* rhm010QueueTable_undo_setup */

/**
 * Cleanup up context undo information.
 *
 * This function will be called after set/commit processing. If you
 * allocated any resources in undo_setup, this is the place to release
 * those resources.
 *
 * This function is called regardless of the success or failure of the set
 * request. If you need to perform different steps for cleanup depending
 * on success or failure, you can add a flag to the rowreq_ctx.
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
rhm010QueueTable_undo_cleanup(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueTable_undo_cleanup",
                "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:452:M: |-> Cleanup rhm010QueueTable undo.
     * Undo storage is in (* rhm010QueueFlowStoppedCount_val_ptr )*
     */

    return rc;
}                               /* rhm010QueueTable_undo_cleanup */

/**
 * commit new values.
 *
 * At this point, you should have done everything you can to ensure that
 * this commit will not fail.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * rhm010QueueTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param rhm010QueueTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
rhm010QueueTable_commit(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;
    int             save_flags;

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueTable_commit",
                "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * save flags, then clear until we actually do something
     */
    save_flags = rowreq_ctx->column_set_flags;
    rowreq_ctx->column_set_flags = 0;

    /*
     * commit rhm010QueueTable data
     * 1) check the column's flag in save_flags to see if it was set.
     * 2) clear the flag when you handle that column
     * 3) set the column's flag in column_set_flags if it needs undo
     *    processing in case of a failure.
     */
    if (save_flags & COLUMN_RHM010QUEUEVHOSTREF_FLAG) {
        save_flags &= ~COLUMN_RHM010QUEUEVHOSTREF_FLAG; /* clear rhm010QueueVhostRef */
        /*
         * TODO:482:o: |-> commit column rhm010QueueVhostRef.
         */
        rc = -1;
        if (-1 == rc) {
            snmp_log(LOG_ERR,
                     "rhm010QueueTable column rhm010QueueVhostRef commit failed\n");
        } else {
            /*
             * set flag, in case we need to undo rhm010QueueVhostRef
             */
            rowreq_ctx->column_set_flags |=
                COLUMN_RHM010QUEUEVHOSTREF_FLAG;
        }
    }

    if (save_flags & COLUMN_RHM010QUEUENAME_FLAG) {
        save_flags &= ~COLUMN_RHM010QUEUENAME_FLAG;     /* clear rhm010QueueName */
        /*
         * TODO:482:o: |-> commit column rhm010QueueName.
         */
        rc = -1;
        if (-1 == rc) {
            snmp_log(LOG_ERR,
                     "rhm010QueueTable column rhm010QueueName commit failed\n");
        } else {
            /*
             * set flag, in case we need to undo rhm010QueueName
             */
            rowreq_ctx->column_set_flags |= COLUMN_RHM010QUEUENAME_FLAG;
        }
    }

    if (save_flags & COLUMN_RHM010QUEUEDURABLE_FLAG) {
        save_flags &= ~COLUMN_RHM010QUEUEDURABLE_FLAG;  /* clear rhm010QueueDurable */
        /*
         * TODO:482:o: |-> commit column rhm010QueueDurable.
         */
        rc = -1;
        if (-1 == rc) {
            snmp_log(LOG_ERR,
                     "rhm010QueueTable column rhm010QueueDurable commit failed\n");
        } else {
            /*
             * set flag, in case we need to undo rhm010QueueDurable
             */
            rowreq_ctx->column_set_flags |= COLUMN_RHM010QUEUEDURABLE_FLAG;
        }
    }

    if (save_flags & COLUMN_RHM010QUEUEAUTODELETE_FLAG) {
        save_flags &= ~COLUMN_RHM010QUEUEAUTODELETE_FLAG;       /* clear rhm010QueueAutoDelete */
        /*
         * TODO:482:o: |-> commit column rhm010QueueAutoDelete.
         */
        rc = -1;
        if (-1 == rc) {
            snmp_log(LOG_ERR,
                     "rhm010QueueTable column rhm010QueueAutoDelete commit failed\n");
        } else {
            /*
             * set flag, in case we need to undo rhm010QueueAutoDelete
             */
            rowreq_ctx->column_set_flags |=
                COLUMN_RHM010QUEUEAUTODELETE_FLAG;
        }
    }

    if (save_flags & COLUMN_RHM010QUEUEEXCLUSIVE_FLAG) {
        save_flags &= ~COLUMN_RHM010QUEUEEXCLUSIVE_FLAG;        /* clear rhm010QueueExclusive */
        /*
         * TODO:482:o: |-> commit column rhm010QueueExclusive.
         */
        rc = -1;
        if (-1 == rc) {
            snmp_log(LOG_ERR,
                     "rhm010QueueTable column rhm010QueueExclusive commit failed\n");
        } else {
            /*
             * set flag, in case we need to undo rhm010QueueExclusive
             */
            rowreq_ctx->column_set_flags |=
                COLUMN_RHM010QUEUEEXCLUSIVE_FLAG;
        }
    }

    /*
     * if we successfully commited this row, set the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags |= MFD_ROW_DIRTY;
    }

    if (save_flags) {
        snmp_log(LOG_ERR, "unhandled columns (0x%x) in commit\n",
                 save_flags);
        return MFD_ERROR;
    }

    return rc;
}                               /* rhm010QueueTable_commit */

/**
 * undo commit new values.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * rhm010QueueTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @param rhm010QueueTable_rowreq_ctx
 *        Pointer to the users context.
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error
 */
int
rhm010QueueTable_undo_commit(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueTable_undo_commit",
                "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:485:M: |-> Undo rhm010QueueTable commit.
     * check the column's flag in rowreq_ctx->column_set_flags to see
     * if it was set during commit, then undo it.
     *
     * eg: if (rowreq_ctx->column_set_flags & COLUMN__FLAG) {}
     */


    /*
     * if we successfully un-commited this row, clear the dirty flag.
     */
    if (MFD_SUCCESS == rc) {
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return rc;
}                               /* rhm010QueueTable_undo_commit */

/*
 * TODO:440:M: Implement rhm010QueueTable node value checks.
 * TODO:450:M: Implement rhm010QueueTable undo functions.
 * TODO:460:M: Implement rhm010QueueTable set functions.
 * TODO:480:M: Implement rhm010QueueTable commit functions.
 */
/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010QueueEntry.rhm010QueueVhostRef
 * rhm010QueueVhostRef is subid 1 of rhm010QueueEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.6.1.1.1
 * Description:
Queue vhostRef
                     Additional info ( nodeType:property, references:Vhost, index:y, parentRef:y )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is ObjId (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010QueueVhostRef_val_ptr
 *        A char containing the new value.
 * @param rhm010QueueVhostRef_val_ptr_len
 *        The size (in bytes) of the data pointed to by rhm010QueueVhostRef_val_ptr
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rhm010QueueTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_OCTET_STR
 *    The length is < sizeof(rowreq_ctx->data.rhm010QueueVhostRef).
 *    The length is in (one of) the range set(s):  0 - 255
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rhm010QueueVhostRef_check_value(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                                char *rhm010QueueVhostRef_val_ptr,
                                size_t rhm010QueueVhostRef_val_ptr_len)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueVhostRef_check_value",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != rhm010QueueVhostRef_val_ptr);

    /*
     * TODO:441:o: |-> Check for valid rhm010QueueVhostRef value.
     */

    return MFD_SUCCESS;         /* rhm010QueueVhostRef value not illegal */
}                               /* rhm010QueueVhostRef_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rhm010QueueTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rhm010QueueVhostRef_undo_setup(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueVhostRef_undo_setup",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rhm010QueueVhostRef undo.
     */
    /*
     * copy rhm010QueueVhostRef and rhm010QueueVhostRef_len data
     * set rowreq_ctx->undo->rhm010QueueVhostRef from rowreq_ctx->data.rhm010QueueVhostRef
     */
    memcpy(rowreq_ctx->undo->rhm010QueueVhostRef,
           rowreq_ctx->data.rhm010QueueVhostRef,
           (rowreq_ctx->data.rhm010QueueVhostRef_len *
            sizeof(rowreq_ctx->undo->rhm010QueueVhostRef[0])));
    rowreq_ctx->undo->rhm010QueueVhostRef_len =
        rowreq_ctx->data.rhm010QueueVhostRef_len;


    return MFD_SUCCESS;
}                               /* rhm010QueueVhostRef_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rhm010QueueVhostRef_val_ptr
 *        A char containing the new value.
 * @param rhm010QueueVhostRef_val_ptr_len
 *        The size (in bytes) of the data pointed to by rhm010QueueVhostRef_val_ptr
 */
int
rhm010QueueVhostRef_set(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                        char *rhm010QueueVhostRef_val_ptr,
                        size_t rhm010QueueVhostRef_val_ptr_len)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueVhostRef_set",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != rhm010QueueVhostRef_val_ptr);

    /*
     * TODO:461:M: |-> Set rhm010QueueVhostRef value.
     * set rhm010QueueVhostRef value in rowreq_ctx->data
     */
    memcpy(rowreq_ctx->data.rhm010QueueVhostRef,
           rhm010QueueVhostRef_val_ptr, rhm010QueueVhostRef_val_ptr_len);
    /** convert bytes to number of char */
    rowreq_ctx->data.rhm010QueueVhostRef_len =
        rhm010QueueVhostRef_val_ptr_len /
        sizeof(rhm010QueueVhostRef_val_ptr[0]);

    return MFD_SUCCESS;
}                               /* rhm010QueueVhostRef_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rhm010QueueVhostRef_undo(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueVhostRef_undo",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rhm010QueueVhostRef undo.
     */
    /*
     * copy rhm010QueueVhostRef and rhm010QueueVhostRef_len data
     * set rowreq_ctx->data.rhm010QueueVhostRef from rowreq_ctx->undo->rhm010QueueVhostRef
     */
    memcpy(rowreq_ctx->data.rhm010QueueVhostRef,
           rowreq_ctx->undo->rhm010QueueVhostRef,
           (rowreq_ctx->undo->rhm010QueueVhostRef_len *
            sizeof(rowreq_ctx->data.rhm010QueueVhostRef[0])));
    rowreq_ctx->data.rhm010QueueVhostRef_len =
        rowreq_ctx->undo->rhm010QueueVhostRef_len;


    return MFD_SUCCESS;
}                               /* rhm010QueueVhostRef_undo */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010QueueEntry.rhm010QueueName
 * rhm010QueueName is subid 2 of rhm010QueueEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.6.1.1.2
 * Description:
Queue name
                     Additional info ( nodeType:property, index:y )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is Sstr (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010QueueName_val_ptr
 *        A char containing the new value.
 * @param rhm010QueueName_val_ptr_len
 *        The size (in bytes) of the data pointed to by rhm010QueueName_val_ptr
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rhm010QueueTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_OCTET_STR
 *    The length is < sizeof(rowreq_ctx->data.rhm010QueueName).
 *    The length is in (one of) the range set(s):  0 - 255
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rhm010QueueName_check_value(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                            char *rhm010QueueName_val_ptr,
                            size_t rhm010QueueName_val_ptr_len)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueName_check_value",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != rhm010QueueName_val_ptr);

    /*
     * TODO:441:o: |-> Check for valid rhm010QueueName value.
     */

    return MFD_SUCCESS;         /* rhm010QueueName value not illegal */
}                               /* rhm010QueueName_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rhm010QueueTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rhm010QueueName_undo_setup(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueName_undo_setup",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rhm010QueueName undo.
     */
    /*
     * copy rhm010QueueName and rhm010QueueName_len data
     * set rowreq_ctx->undo->rhm010QueueName from rowreq_ctx->data.rhm010QueueName
     */
    memcpy(rowreq_ctx->undo->rhm010QueueName,
           rowreq_ctx->data.rhm010QueueName,
           (rowreq_ctx->data.rhm010QueueName_len *
            sizeof(rowreq_ctx->undo->rhm010QueueName[0])));
    rowreq_ctx->undo->rhm010QueueName_len =
        rowreq_ctx->data.rhm010QueueName_len;


    return MFD_SUCCESS;
}                               /* rhm010QueueName_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rhm010QueueName_val_ptr
 *        A char containing the new value.
 * @param rhm010QueueName_val_ptr_len
 *        The size (in bytes) of the data pointed to by rhm010QueueName_val_ptr
 */
int
rhm010QueueName_set(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                    char *rhm010QueueName_val_ptr,
                    size_t rhm010QueueName_val_ptr_len)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueName_set",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);
    netsnmp_assert(NULL != rhm010QueueName_val_ptr);

    /*
     * TODO:461:M: |-> Set rhm010QueueName value.
     * set rhm010QueueName value in rowreq_ctx->data
     */
    memcpy(rowreq_ctx->data.rhm010QueueName, rhm010QueueName_val_ptr,
           rhm010QueueName_val_ptr_len);
    /** convert bytes to number of char */
    rowreq_ctx->data.rhm010QueueName_len =
        rhm010QueueName_val_ptr_len / sizeof(rhm010QueueName_val_ptr[0]);

    return MFD_SUCCESS;
}                               /* rhm010QueueName_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rhm010QueueName_undo(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueName_undo",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rhm010QueueName undo.
     */
    /*
     * copy rhm010QueueName and rhm010QueueName_len data
     * set rowreq_ctx->data.rhm010QueueName from rowreq_ctx->undo->rhm010QueueName
     */
    memcpy(rowreq_ctx->data.rhm010QueueName,
           rowreq_ctx->undo->rhm010QueueName,
           (rowreq_ctx->undo->rhm010QueueName_len *
            sizeof(rowreq_ctx->data.rhm010QueueName[0])));
    rowreq_ctx->data.rhm010QueueName_len =
        rowreq_ctx->undo->rhm010QueueName_len;


    return MFD_SUCCESS;
}                               /* rhm010QueueName_undo */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010QueueEntry.rhm010QueueDurable
 * rhm010QueueDurable is subid 3 of rhm010QueueEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.6.1.1.3
 * Description:
Queue durable
                     Additional info ( nodeType:property )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010QueueDurable_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rhm010QueueTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rhm010QueueDurable_check_value(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                               u_long rhm010QueueDurable_val)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueDurable_check_value",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid rhm010QueueDurable value.
     */

    return MFD_SUCCESS;         /* rhm010QueueDurable value not illegal */
}                               /* rhm010QueueDurable_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rhm010QueueTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rhm010QueueDurable_undo_setup(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueDurable_undo_setup",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rhm010QueueDurable undo.
     */
    /*
     * copy rhm010QueueDurable data
     * set rowreq_ctx->undo->rhm010QueueDurable from rowreq_ctx->data.rhm010QueueDurable
     */
    rowreq_ctx->undo->rhm010QueueDurable =
        rowreq_ctx->data.rhm010QueueDurable;


    return MFD_SUCCESS;
}                               /* rhm010QueueDurable_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rhm010QueueDurable_val
 *        A long containing the new value.
 */
int
rhm010QueueDurable_set(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                       u_long rhm010QueueDurable_val)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueDurable_set",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set rhm010QueueDurable value.
     * set rhm010QueueDurable value in rowreq_ctx->data
     */
    rowreq_ctx->data.rhm010QueueDurable = rhm010QueueDurable_val;

    return MFD_SUCCESS;
}                               /* rhm010QueueDurable_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rhm010QueueDurable_undo(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueDurable_undo",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rhm010QueueDurable undo.
     */
    /*
     * copy rhm010QueueDurable data
     * set rowreq_ctx->data.rhm010QueueDurable from rowreq_ctx->undo->rhm010QueueDurable
     */
    rowreq_ctx->data.rhm010QueueDurable =
        rowreq_ctx->undo->rhm010QueueDurable;


    return MFD_SUCCESS;
}                               /* rhm010QueueDurable_undo */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010QueueEntry.rhm010QueueAutoDelete
 * rhm010QueueAutoDelete is subid 4 of rhm010QueueEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.6.1.1.4
 * Description:
Queue autoDelete
                     Additional info ( nodeType:property )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010QueueAutoDelete_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rhm010QueueTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rhm010QueueAutoDelete_check_value(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                                  u_long rhm010QueueAutoDelete_val)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueAutoDelete_check_value", "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid rhm010QueueAutoDelete value.
     */

    return MFD_SUCCESS;         /* rhm010QueueAutoDelete value not illegal */
}                               /* rhm010QueueAutoDelete_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rhm010QueueTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rhm010QueueAutoDelete_undo_setup(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueAutoDelete_undo_setup", "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rhm010QueueAutoDelete undo.
     */
    /*
     * copy rhm010QueueAutoDelete data
     * set rowreq_ctx->undo->rhm010QueueAutoDelete from rowreq_ctx->data.rhm010QueueAutoDelete
     */
    rowreq_ctx->undo->rhm010QueueAutoDelete =
        rowreq_ctx->data.rhm010QueueAutoDelete;


    return MFD_SUCCESS;
}                               /* rhm010QueueAutoDelete_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rhm010QueueAutoDelete_val
 *        A long containing the new value.
 */
int
rhm010QueueAutoDelete_set(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                          u_long rhm010QueueAutoDelete_val)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueAutoDelete_set",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set rhm010QueueAutoDelete value.
     * set rhm010QueueAutoDelete value in rowreq_ctx->data
     */
    rowreq_ctx->data.rhm010QueueAutoDelete = rhm010QueueAutoDelete_val;

    return MFD_SUCCESS;
}                               /* rhm010QueueAutoDelete_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rhm010QueueAutoDelete_undo(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueAutoDelete_undo",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rhm010QueueAutoDelete undo.
     */
    /*
     * copy rhm010QueueAutoDelete data
     * set rowreq_ctx->data.rhm010QueueAutoDelete from rowreq_ctx->undo->rhm010QueueAutoDelete
     */
    rowreq_ctx->data.rhm010QueueAutoDelete =
        rowreq_ctx->undo->rhm010QueueAutoDelete;


    return MFD_SUCCESS;
}                               /* rhm010QueueAutoDelete_undo */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010QueueEntry.rhm010QueueExclusive
 * rhm010QueueExclusive is subid 5 of rhm010QueueEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.6.1.1.5
 * Description:
Queue exclusive
                     Additional info ( nodeType:property )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   1
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Check that the proposed new value is potentially valid.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010QueueExclusive_val
 *        A long containing the new value.
 *
 * @retval MFD_SUCCESS        : incoming value is legal
 * @retval MFD_NOT_VALID_NOW  : incoming value is not valid now
 * @retval MFD_NOT_VALID_EVER : incoming value is never valid
 *
 * This is the place to check for requirements that are not
 * expressed in the mib syntax (for example, a requirement that
 * is detailed in the description for an object).
 *
 * You should check that the requested change between the undo value and the
 * new value is legal (ie, the transistion from one value to another
 * is legal).
 *      
 *@note
 * This check is only to determine if the new value
 * is \b potentially valid. This is the first check of many, and
 * is one of the simplest ones.
 * 
 *@note
 * this is not the place to do any checks for values
 * which depend on some other value in the mib. Those
 * types of checks should be done in the
 * rhm010QueueTable_check_dependencies() function.
 *
 * The following checks have already been done for you:
 *    The syntax is ASN_INTEGER
 *    The value is one of  true(1), false(2)
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 *
 */
int
rhm010QueueExclusive_check_value(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                                 u_long rhm010QueueExclusive_val)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueExclusive_check_value", "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:441:o: |-> Check for valid rhm010QueueExclusive value.
     */

    return MFD_SUCCESS;         /* rhm010QueueExclusive value not illegal */
}                               /* rhm010QueueExclusive_check_value */

/**
 * Save old value information
 *
 * @param rowreq_ctx
 *        Pointer to the table context (rhm010QueueTable_rowreq_ctx)
 *
 * @retval MFD_SUCCESS : success
 * @retval MFD_ERROR   : error. set will fail.
 *
 * This function will be called after the table level undo setup function
 * rhm010QueueTable_undo_setup has been called.
 *
 *@note
 * this function will only be called if a new value is set for this column.
 *
 * If there is any setup specific to a particular column (e.g. allocating
 * memory for a string), you should do that setup in this function, so it
 * won't be done unless it is necessary.
 */
int
rhm010QueueExclusive_undo_setup(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueExclusive_undo_setup",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:455:o: |-> Setup rhm010QueueExclusive undo.
     */
    /*
     * copy rhm010QueueExclusive data
     * set rowreq_ctx->undo->rhm010QueueExclusive from rowreq_ctx->data.rhm010QueueExclusive
     */
    rowreq_ctx->undo->rhm010QueueExclusive =
        rowreq_ctx->data.rhm010QueueExclusive;


    return MFD_SUCCESS;
}                               /* rhm010QueueExclusive_undo_setup */

/**
 * Set the new value.
 *
 * @param rowreq_ctx
 *        Pointer to the users context. You should know how to
 *        manipulate the value from this object.
 * @param rhm010QueueExclusive_val
 *        A long containing the new value.
 */
int
rhm010QueueExclusive_set(rhm010QueueTable_rowreq_ctx * rowreq_ctx,
                         u_long rhm010QueueExclusive_val)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueExclusive_set",
                "called\n"));

    /** should never get a NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:461:M: |-> Set rhm010QueueExclusive value.
     * set rhm010QueueExclusive value in rowreq_ctx->data
     */
    rowreq_ctx->data.rhm010QueueExclusive = rhm010QueueExclusive_val;

    return MFD_SUCCESS;
}                               /* rhm010QueueExclusive_set */

/**
 * undo the previous set.
 *
 * @param rowreq_ctx
 *        Pointer to the users context.
 */
int
rhm010QueueExclusive_undo(rhm010QueueTable_rowreq_ctx * rowreq_ctx)
{

    DEBUGMSGTL(("verbose:rhm010QueueTable:rhm010QueueExclusive_undo",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:456:o: |-> Clean up rhm010QueueExclusive undo.
     */
    /*
     * copy rhm010QueueExclusive data
     * set rowreq_ctx->data.rhm010QueueExclusive from rowreq_ctx->undo->rhm010QueueExclusive
     */
    rowreq_ctx->data.rhm010QueueExclusive =
        rowreq_ctx->undo->rhm010QueueExclusive;


    return MFD_SUCCESS;
}                               /* rhm010QueueExclusive_undo */

/**
 * check dependencies
 *
 * This is useful for for tables which have dependencies between columns
 * (or rows, or tables). For example, two columns allocating a percentage
 * of something add up 100%.
 *
 * Should you need different behavior depending on which columns were
 * set, rowreq_ctx->column_set_flags will indicate which writeable columns were
 * set. The definitions for the COLUMN_*_FLAG bits can be found in
 * rhm010QueueTable_oids.h.
 * A new row will have the MFD_ROW_CREATED bit set in rowreq_flags.
 *
 * @retval MFD_SUCCESS all the changes to the row are legal
 * @retval MFD_ERROR   one or more changes are not legal
 *
 * (see README-table-rhm010QueueTable if you don't have dependencies)
 */
int
rhm010QueueTable_check_dependencies(rhm010QueueTable_rowreq_ctx *
                                    rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("internal:rhm010QueueTable:rhm010QueueTable_check_dependencies", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:470:o: Check rhm010QueueTable row dependencies.
     * check that all new value are legal and consistent with each other
     */
    return rc;
}                               /* rhm010QueueTable_check_dependencies */

/** @} */
