/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "../qpid_api.h"

/*
 * include our parent header 
 */
#include "ConnectionTable.h"


#include "ConnectionTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table brokerConnectionTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * QPID-MESSAGING-MIB::brokerConnectionTable is subid 1 of brokerConnections.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.18060.5672.1.1.10.1, length: 12
 */

/**
 * initialization for brokerConnectionTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param brokerConnectionTable_reg
 *        Pointer to brokerConnectionTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
brokerConnectionTable_init_data(brokerConnectionTable_registration *
                                brokerConnectionTable_reg)
{
    DEBUGMSGTL(("verbose:brokerConnectionTable:brokerConnectionTable_init_data", "called\n"));

    /*
     * TODO:303:o: Initialize brokerConnectionTable data.
     */
    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     * if you are the sole writer for the file, you could
     * open it here. However, as stated earlier, we are assuming
     * the worst case, which in this case means that the file is
     * written to by someone else, and might not even exist when
     * we start up. So we can't do anything here.
     */
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/

    return MFD_SUCCESS;
}                               /* brokerConnectionTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
brokerConnectionTable_container_init(netsnmp_container **
                                     container_ptr_ptr,
                                     netsnmp_cache * cache)
{
    DEBUGMSGTL(("verbose:brokerConnectionTable:brokerConnectionTable_container_init", "called\n"));

    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,
                 "bad container param to brokerConnectionTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,
                 "bad cache param to brokerConnectionTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up brokerConnectionTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = brokerCONNECTIONTABLE_CACHE_TIMEOUT;       /* seconds */
    //cache->flags |= NETSNMP_CACHE_PRELOAD;
}                               /* brokerConnectionTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before brokerConnectionTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
brokerConnectionTable_container_shutdown(netsnmp_container * container_ptr)
{
    DEBUGMSGTL(("verbose:brokerConnectionTable:brokerConnectionTable_container_shutdown", "called\n"));

    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,
                 "bad params to brokerConnectionTable_container_shutdown\n");
        return;
    }

}                               /* brokerConnectionTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement brokerConnectionTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  brokerConnectionTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
brokerConnectionTable_container_load(netsnmp_container * container)
{
    brokerConnectionTable_rowreq_ctx *rowreq_ctx;
    size_t          count = 0;

    /*
     * temporary storage for index values
     */
    /*
     * brokerConnectionInternalIndex(21)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/r/d/h
     */
    u_long          brokerConnectionInternalIndex;
    brokerConnectionTable_data qmfData;

    uint64_t u64Data;

    void *pEvent = qpidGet("connection");

    int index;
    uint objects;
    objects = qpidGetCount(pEvent);

    brokerConnectionInternalIndex = 0;
    for (index = 0; index < objects; ++index) {

    	void * pRow = qpidGetDataRow(pEvent, index);
    	if (!pRow)
    		continue;

        strncpy(qmfData.brokerConnectionVhostRef,
        		qpidGetString(pRow, "vhostRef"), 254);
        qmfData.brokerConnectionVhostRef_len = strlen(qmfData.brokerConnectionVhostRef) + 1;

        strncpy(qmfData.brokerConnectionAddress,
        		qpidGetString(pRow, "address"), 254);
        qmfData.brokerConnectionAddress_len = strlen(qmfData.brokerConnectionAddress) + 1;

        qmfData.brokerConnectionIncoming = qpidGetBool(pRow, "incoming");
        qmfData.brokerConnectionSystemConnection = qpidGetBool(pRow, "systemConnection");
        qmfData.brokerConnectionUserProxyAuth = qpidGetBool(pRow, "userProxyAuth");
        qmfData.brokerConnectionFederationLink = qpidGetBool(pRow, "federationLink");

        strncpy(qmfData.brokerConnectionAuthIdentity,
        		qpidGetString(pRow, "authIdentity"), 254);
        qmfData.brokerConnectionAuthIdentity_len = strlen(qmfData.brokerConnectionAuthIdentity) + 1;

        strncpy(qmfData.brokerConnectionRemoteProcessName,
        		qpidGetString(pRow, "remoteProcessName"), 65534);
        qmfData.brokerConnectionRemoteProcessName_len = strlen(qmfData.brokerConnectionRemoteProcessName) + 1;

        qmfData.brokerConnectionRemotePid = qpidGetU32(pRow, "remotePid");
        qmfData.brokerConnectionRemoteParentPid = qpidGetU32(pRow, "remoteParentPid");

        qmfData.brokerConnectionShadow = qpidGetBool(pRow, "shadow");

        strncpy(qmfData.brokerConnectionSaslMechanism,
        		qpidGetString(pRow, "saslMechanism"), 254);
        qmfData.brokerConnectionSaslMechanism_len = strlen(qmfData.brokerConnectionSaslMechanism) + 1;

        qmfData.brokerConnectionSaslSsf = qpidGetU16(pRow, "saslSsf");
        qmfData.brokerConnectionClosing = qpidGetBool(pRow, "closing");

        u64Data = qpidGetU64(pRow, "framesFromClient");
        qmfData.brokerConnectionFramesFromClient.high = HIGHLONG(u64Data);
        qmfData.brokerConnectionFramesFromClient.low = LOWLONG(u64Data);

        u64Data = qpidGetU64(pRow, "framesToClient");
        qmfData.brokerConnectionFramesToClient.high = HIGHLONG(u64Data);
        qmfData.brokerConnectionFramesToClient.low = LOWLONG(u64Data);

        u64Data = qpidGetU64(pRow, "bytesFromClient");
        qmfData.brokerConnectionBytesFromClient.high = HIGHLONG(u64Data);
        qmfData.brokerConnectionBytesFromClient.low = LOWLONG(u64Data);

        u64Data = qpidGetU64(pRow, "bytesToClient");
        qmfData.brokerConnectionBytesToClient.high = HIGHLONG(u64Data);
        qmfData.brokerConnectionBytesToClient.low = LOWLONG(u64Data);

        u64Data = qpidGetU64(pRow, "msgsFromClient");
        qmfData.brokerConnectionMsgsFromClient.high = HIGHLONG(u64Data);
        qmfData.brokerConnectionMsgsFromClient.low = LOWLONG(u64Data);

        u64Data = qpidGetU64(pRow, "msgsToClient");
        qmfData.brokerConnectionMsgsToClient.high = HIGHLONG(u64Data);
        qmfData.brokerConnectionMsgsToClient.low = LOWLONG(u64Data);

        /*
         * TODO:352:M: |   |-> set indexes in new brokerConnectionTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = brokerConnectionTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if (MFD_SUCCESS !=
            brokerConnectionTable_indexes_set(rowreq_ctx,
                                              brokerConnectionInternalIndex))
        {
            snmp_log(LOG_ERR,
                     "error setting index while loading "
                     "brokerConnectionTable data.\n");
            brokerConnectionTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }
        brokerConnectionInternalIndex++;

        /*
         * setup/save data for brokerConnectionVhostRef
         * brokerConnectionVhostRef(1)/ObjId/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for brokerConnectionVhostRef data
         */
        if ((NULL == rowreq_ctx->data.brokerConnectionVhostRef) ||
            (rowreq_ctx->data.brokerConnectionVhostRef_len <
             (qmfData.brokerConnectionVhostRef_len *
              sizeof(qmfData.brokerConnectionVhostRef[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (brokerConnectionVhostRef)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.brokerConnectionVhostRef_len =
        		qmfData.brokerConnectionVhostRef_len *
            sizeof(qmfData.brokerConnectionVhostRef[0]);
        memcpy(rowreq_ctx->data.brokerConnectionVhostRef,
        		qmfData.brokerConnectionVhostRef,
        		qmfData.brokerConnectionVhostRef_len *
               sizeof(qmfData.brokerConnectionVhostRef[0]));

        /*
         * setup/save data for brokerConnectionAddress
         * brokerConnectionAddress(2)/Sstr/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for brokerConnectionAddress data
         */
        if ((NULL == rowreq_ctx->data.brokerConnectionAddress) ||
            (rowreq_ctx->data.brokerConnectionAddress_len <
             (qmfData.brokerConnectionAddress_len *
              sizeof(qmfData.brokerConnectionAddress[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (brokerConnectionAddress)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.brokerConnectionAddress_len =
        		qmfData.brokerConnectionAddress_len *
            sizeof(qmfData.brokerConnectionAddress[0]);
        memcpy(rowreq_ctx->data.brokerConnectionAddress,
        		qmfData.brokerConnectionAddress,
        		qmfData.brokerConnectionAddress_len *
               sizeof(qmfData.brokerConnectionAddress[0]));

        /*
         * setup/save data for brokerConnectionIncoming
         * brokerConnectionIncoming(3)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionIncoming =
        		qmfData.brokerConnectionIncoming;

        /*
         * setup/save data for brokerConnectionSystemConnection
         * brokerConnectionSystemConnection(4)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionSystemConnection =
        		qmfData.brokerConnectionSystemConnection;

        /*
         * setup/save data for brokerConnectionUserProxyAuth
         * brokerConnectionUserProxyAuth(5)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionUserProxyAuth =
        		qmfData.brokerConnectionUserProxyAuth;

        /*
         * setup/save data for brokerConnectionFederationLink
         * brokerConnectionFederationLink(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionFederationLink =
        		qmfData.brokerConnectionFederationLink;

        /*
         * setup/save data for brokerConnectionAuthIdentity
         * brokerConnectionAuthIdentity(7)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for brokerConnectionAuthIdentity data
         */
        if ((NULL == rowreq_ctx->data.brokerConnectionAuthIdentity) ||
            (rowreq_ctx->data.brokerConnectionAuthIdentity_len <
             (qmfData.brokerConnectionAuthIdentity_len *
              sizeof(qmfData.brokerConnectionAuthIdentity[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (brokerConnectionAuthIdentity)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.brokerConnectionAuthIdentity_len =
        		qmfData.brokerConnectionAuthIdentity_len *
            sizeof(qmfData.brokerConnectionAuthIdentity[0]);
        memcpy(rowreq_ctx->data.brokerConnectionAuthIdentity,
        		qmfData.brokerConnectionAuthIdentity,
        		qmfData.brokerConnectionAuthIdentity_len *
               sizeof(qmfData.brokerConnectionAuthIdentity[0]));

        /*
         * setup/save data for brokerConnectionRemoteProcessName
         * brokerConnectionRemoteProcessName(8)/Lstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for brokerConnectionRemoteProcessName data
         */
        if ((NULL == rowreq_ctx->data.brokerConnectionRemoteProcessName) ||
            (rowreq_ctx->data.brokerConnectionRemoteProcessName_len <
             (qmfData.brokerConnectionRemoteProcessName_len *
              sizeof(qmfData.brokerConnectionRemoteProcessName[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (brokerConnectionRemoteProcessName)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.brokerConnectionRemoteProcessName_len =
        		qmfData.brokerConnectionRemoteProcessName_len *
            sizeof(qmfData.brokerConnectionRemoteProcessName[0]);
        memcpy(rowreq_ctx->data.brokerConnectionRemoteProcessName,
        		qmfData.brokerConnectionRemoteProcessName,
        		qmfData.brokerConnectionRemoteProcessName_len *
               sizeof(qmfData.brokerConnectionRemoteProcessName[0]));

        /*
         * setup/save data for brokerConnectionRemotePid
         * brokerConnectionRemotePid(9)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionRemotePid =
        		qmfData.brokerConnectionRemotePid;

        /*
         * setup/save data for brokerConnectionRemoteParentPid
         * brokerConnectionRemoteParentPid(10)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionRemoteParentPid =
        		qmfData.brokerConnectionRemoteParentPid;

        /*
         * setup/save data for brokerConnectionShadow
         * brokerConnectionShadow(11)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionShadow = qmfData.brokerConnectionShadow;

        /*
         * setup/save data for brokerConnectionSaslMechanism
         * brokerConnectionSaslMechanism(12)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
    /** no mapping */
        /*
         * make sure there is enough space for brokerConnectionSaslMechanism data
         */
        if ((NULL == rowreq_ctx->data.brokerConnectionSaslMechanism) ||
            (rowreq_ctx->data.brokerConnectionSaslMechanism_len <
             (qmfData.brokerConnectionSaslMechanism_len *
              sizeof(qmfData.brokerConnectionSaslMechanism[0])))) {
            snmp_log(LOG_ERR,
                     "not enough space for value (brokerConnectionSaslMechanism)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.brokerConnectionSaslMechanism_len =
        		qmfData.brokerConnectionSaslMechanism_len *
            sizeof(qmfData.brokerConnectionSaslMechanism[0]);
        memcpy(rowreq_ctx->data.brokerConnectionSaslMechanism,
        		qmfData.brokerConnectionSaslMechanism,
        		qmfData.brokerConnectionSaslMechanism_len *
               sizeof(qmfData.brokerConnectionSaslMechanism[0]));

        /*
         * setup/save data for brokerConnectionSaslSsf
         * brokerConnectionSaslSsf(13)/Uint16/ASN_INTEGER/long(long)//l/A/w/e/r/d/H
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionSaslSsf = qmfData.brokerConnectionSaslSsf;

        /*
         * setup/save data for brokerConnectionClosing
         * brokerConnectionClosing(14)/TruthValue/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionClosing = qmfData.brokerConnectionClosing;

        /*
         * setup/save data for brokerConnectionFramesFromClient
         * brokerConnectionFramesFromClient(15)/COUNTER64/ASN_COUNTER64/U64(U64)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionFramesFromClient.high =
        		qmfData.brokerConnectionFramesFromClient.high;
        rowreq_ctx->data.brokerConnectionFramesFromClient.low =
        		qmfData.brokerConnectionFramesFromClient.low;

        /*
         * setup/save data for brokerConnectionFramesToClient
         * brokerConnectionFramesToClient(16)/COUNTER64/ASN_COUNTER64/U64(U64)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionFramesToClient.high =
        		qmfData.brokerConnectionFramesToClient.high;
        rowreq_ctx->data.brokerConnectionFramesToClient.low =
        		qmfData.brokerConnectionFramesToClient.low;

        /*
         * setup/save data for brokerConnectionBytesFromClient
         * brokerConnectionBytesFromClient(17)/COUNTER64/ASN_COUNTER64/U64(U64)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionBytesFromClient.high =
        		qmfData.brokerConnectionBytesFromClient.high;
        rowreq_ctx->data.brokerConnectionBytesFromClient.low =
        		qmfData.brokerConnectionBytesFromClient.low;

        /*
         * setup/save data for brokerConnectionBytesToClient
         * brokerConnectionBytesToClient(18)/COUNTER64/ASN_COUNTER64/U64(U64)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionBytesToClient.high =
        		qmfData.brokerConnectionBytesToClient.high;
        rowreq_ctx->data.brokerConnectionBytesToClient.low =
        		qmfData.brokerConnectionBytesToClient.low;

        /*
         * setup/save data for brokerConnectionMsgsFromClient
         * brokerConnectionMsgsFromClient(19)/COUNTER64/ASN_COUNTER64/U64(U64)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionMsgsFromClient.high =
        		qmfData.brokerConnectionMsgsFromClient.high;
        rowreq_ctx->data.brokerConnectionMsgsFromClient.low =
        		qmfData.brokerConnectionMsgsFromClient.low;

        /*
         * setup/save data for brokerConnectionMsgsToClient
         * brokerConnectionMsgsToClient(20)/COUNTER64/ASN_COUNTER64/U64(U64)//l/A/w/e/r/d/h
         */
    /** no mapping */
        rowreq_ctx->data.brokerConnectionMsgsToClient.high =
        		qmfData.brokerConnectionMsgsToClient.high;
        rowreq_ctx->data.brokerConnectionMsgsToClient.low =
        		qmfData.brokerConnectionMsgsToClient.low;


        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
        qpidReleaseDataRow(pRow);


    }
    qpidRelease(pEvent);

    DEBUGMSGT(("verbose:brokerConnectionTable:brokerConnectionTable_container_load", "inserted %d records\n", count));

    return MFD_SUCCESS;
}                               /* brokerConnectionTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
brokerConnectionTable_container_free(netsnmp_container * container)
{
    DEBUGMSGTL(("verbose:brokerConnectionTable:brokerConnectionTable_container_free", "called\n"));

    /*
     * TODO:380:M: Free brokerConnectionTable container data.
     */
}                               /* brokerConnectionTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
brokerConnectionTable_row_prep(brokerConnectionTable_rowreq_ctx *
                               rowreq_ctx)
{
    DEBUGMSGTL(("verbose:brokerConnectionTable:brokerConnectionTable_row_prep", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
}                               /* brokerConnectionTable_row_prep */

/*
 * TODO:420:r: Implement brokerConnectionTable index validation.
 */
/*---------------------------------------------------------------------
 * QPID-MESSAGING-MIB::brokerConnectionEntry.brokerConnectionInternalIndex
 * brokerConnectionInternalIndex is subid 21 of brokerConnectionEntry.
 * Its status is Current, and its access level is NoAccess.
 * OID: .1.3.6.1.4.1.18060.5672.1.1.10.1.1.21
 * Description:
Internal index for connection table
 *
 * Attributes:
 *   accessible 0     isscalar 0     enums  0      hasdefval 0
 *   readable   0     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 *
 *
 *
 * NOTE: NODE brokerConnectionInternalIndex IS NOT ACCESSIBLE
 *
 *
 */
/**
 * check validity of brokerConnectionInternalIndex index portion
 *
 * @retval MFD_SUCCESS   : the incoming value is legal
 * @retval MFD_ERROR     : the incoming value is NOT legal
 *
 * @note this is not the place to do any checks for the sanity
 *       of multiple indexes. Those types of checks should be done in the
 *       brokerConnectionTable_validate_index() function.
 *
 * @note Also keep in mind that if the index refers to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 * The following checks have already been done for you:
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 */
int
brokerConnectionInternalIndex_check_index(brokerConnectionTable_rowreq_ctx
                                          * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:brokerConnectionTable:brokerConnectionInternalIndex_check_index", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:426:M: |-> Check brokerConnectionTable index brokerConnectionInternalIndex.
     * check that index value in the table context is legal.
     * (rowreq_ctx->tbl_index.brokerConnectionInternalIndex)
     */

    return MFD_SUCCESS;         /* brokerConnectionInternalIndex index ok */
}                               /* brokerConnectionInternalIndex_check_index */

/**
 * verify specified index is valid.
 *
 * This check is independent of whether or not the values specified for
 * the columns of the new row are valid. Column values and row consistency
 * will be checked later. At this point, only the index values should be
 * checked.
 *
 * All of the individual index validation functions have been called, so this
 * is the place to make sure they are valid as a whole when combined. If
 * you only have one index, then you probably don't need to do anything else
 * here.
 * 
 * @note Keep in mind that if the indexes refer to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 *
 * @param brokerConnectionTable_reg
 *        Pointer to the user registration data
 * @param brokerConnectionTable_rowreq_ctx
 *        Pointer to the users context.
 * @retval MFD_SUCCESS            : success
 * @retval MFD_CANNOT_CREATE_NOW  : index not valid right now
 * @retval MFD_CANNOT_CREATE_EVER : index never valid
 */
int
brokerConnectionTable_validate_index(brokerConnectionTable_registration *
                                     brokerConnectionTable_reg,
                                     brokerConnectionTable_rowreq_ctx *
                                     rowreq_ctx)
{
    int             rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:brokerConnectionTable:brokerConnectionTable_validate_index", "called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:430:M: |-> Validate potential brokerConnectionTable index.
     */
    if (1) {
        snmp_log(LOG_WARNING, "invalid index for a new row in the "
                 "brokerConnectionTable table.\n");
        /*
         * determine failure type.
         *
         * If the index could not ever be created, return MFD_NOT_EVER
         * If the index can not be created under the present circumstances
         * (even though it could be created under other circumstances),
         * return MFD_NOT_NOW.
         */
        if (0) {
            return MFD_CANNOT_CREATE_EVER;
        } else {
            return MFD_CANNOT_CREATE_NOW;
        }
    }

    return rc;
}                               /* brokerConnectionTable_validate_index */

/** @} */
