/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file brokerConnectionTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef brokerCONNECTIONTABLE_DATA_GET_H
#define brokerCONNECTIONTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table brokerConnectionTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * QPID-MESSAGING-MIB::brokerConnectionTable is subid 1 of brokerConnections.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18060.5672.1.1.10.1, length: 12
     */
    /*
     * indexes
     */

    int            
        brokerConnectionVhostRef_get(brokerConnectionTable_rowreq_ctx *
                                     rowreq_ctx,
                                     char
                                     **brokerConnectionVhostRef_val_ptr_ptr,
                                     size_t
                                     *brokerConnectionVhostRef_val_ptr_len_ptr);
    int            
        brokerConnectionAddress_get(brokerConnectionTable_rowreq_ctx *
                                    rowreq_ctx,
                                    char
                                    **brokerConnectionAddress_val_ptr_ptr,
                                    size_t
                                    *brokerConnectionAddress_val_ptr_len_ptr);
    int            
        brokerConnectionIncoming_get(brokerConnectionTable_rowreq_ctx *
                                     rowreq_ctx,
                                     u_long *
                                     brokerConnectionIncoming_val_ptr);
    int            
        brokerConnectionSystemConnection_get
        (brokerConnectionTable_rowreq_ctx * rowreq_ctx,
         u_long * brokerConnectionSystemConnection_val_ptr);
    int            
        brokerConnectionUserProxyAuth_get(brokerConnectionTable_rowreq_ctx
                                          * rowreq_ctx,
                                          u_long *
                                          brokerConnectionUserProxyAuth_val_ptr);
    int            
        brokerConnectionFederationLink_get(brokerConnectionTable_rowreq_ctx
                                           * rowreq_ctx,
                                           u_long *
                                           brokerConnectionFederationLink_val_ptr);
    int            
        brokerConnectionAuthIdentity_get(brokerConnectionTable_rowreq_ctx *
                                         rowreq_ctx,
                                         char
                                         **brokerConnectionAuthIdentity_val_ptr_ptr,
                                         size_t
                                         *brokerConnectionAuthIdentity_val_ptr_len_ptr);
    int            
        brokerConnectionRemoteProcessName_get
        (brokerConnectionTable_rowreq_ctx * rowreq_ctx,
         char **brokerConnectionRemoteProcessName_val_ptr_ptr,
         size_t *brokerConnectionRemoteProcessName_val_ptr_len_ptr);
    int            
        brokerConnectionRemotePid_get(brokerConnectionTable_rowreq_ctx *
                                      rowreq_ctx,
                                      u_long *
                                      brokerConnectionRemotePid_val_ptr);
    int            
        brokerConnectionRemoteParentPid_get
        (brokerConnectionTable_rowreq_ctx * rowreq_ctx,
         u_long * brokerConnectionRemoteParentPid_val_ptr);
    int            
        brokerConnectionShadow_get(brokerConnectionTable_rowreq_ctx *
                                   rowreq_ctx,
                                   u_long *
                                   brokerConnectionShadow_val_ptr);
    int            
        brokerConnectionSaslMechanism_get(brokerConnectionTable_rowreq_ctx
                                          * rowreq_ctx,
                                          char
                                          **brokerConnectionSaslMechanism_val_ptr_ptr,
                                          size_t
                                          *brokerConnectionSaslMechanism_val_ptr_len_ptr);
    int            
        brokerConnectionSaslSsf_get(brokerConnectionTable_rowreq_ctx *
                                    rowreq_ctx,
                                    long *brokerConnectionSaslSsf_val_ptr);
    int            
        brokerConnectionClosing_get(brokerConnectionTable_rowreq_ctx *
                                    rowreq_ctx,
                                    u_long *
                                    brokerConnectionClosing_val_ptr);
    int            
        brokerConnectionFramesFromClient_get
        (brokerConnectionTable_rowreq_ctx * rowreq_ctx,
         U64 * brokerConnectionFramesFromClient_val_ptr);
    int            
        brokerConnectionFramesToClient_get(brokerConnectionTable_rowreq_ctx
                                           * rowreq_ctx,
                                           U64 *
                                           brokerConnectionFramesToClient_val_ptr);
    int            
        brokerConnectionBytesFromClient_get
        (brokerConnectionTable_rowreq_ctx * rowreq_ctx,
         U64 * brokerConnectionBytesFromClient_val_ptr);
    int            
        brokerConnectionBytesToClient_get(brokerConnectionTable_rowreq_ctx
                                          * rowreq_ctx,
                                          U64 *
                                          brokerConnectionBytesToClient_val_ptr);
    int            
        brokerConnectionMsgsFromClient_get(brokerConnectionTable_rowreq_ctx
                                           * rowreq_ctx,
                                           U64 *
                                           brokerConnectionMsgsFromClient_val_ptr);
    int            
        brokerConnectionMsgsToClient_get(brokerConnectionTable_rowreq_ctx *
                                         rowreq_ctx,
                                         U64 *
                                         brokerConnectionMsgsToClient_val_ptr);


    int            
        brokerConnectionTable_indexes_set_tbl_idx
        (brokerConnectionTable_mib_index * tbl_idx,
         u_long brokerConnectionInternalIndex_val);
    int            
        brokerConnectionTable_indexes_set(brokerConnectionTable_rowreq_ctx
                                          * rowreq_ctx,
                                          u_long
                                          brokerConnectionInternalIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* brokerCONNECTIONTABLE_DATA_GET_H */
/** @} */
