/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "rhm010SessionTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement rhm010SessionTable get routines.
 * TODO:240:M: Implement rhm010SessionTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rhm010SessionTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * MRG-MESSAGING-MIB::rhm010SessionTable is subid 1 of rhm010Sessions.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1, length: 12
 */

/*
 * ---------------------------------------------------------------------
 * * TODO:200:r: Implement rhm010SessionTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param rhm010SessionInternalIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
rhm010SessionTable_indexes_set_tbl_idx(rhm010SessionTable_mib_index *
                                       tbl_idx,
                                       u_long
                                       rhm010SessionInternalIndex_val)
{
    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionTable_indexes_set_tbl_idx", "called\n"));

    /*
     * rhm010SessionInternalIndex(15)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/r/d/h 
     */
    tbl_idx->rhm010SessionInternalIndex = rhm010SessionInternalIndex_val;


    return MFD_SUCCESS;
}                               /* rhm010SessionTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
rhm010SessionTable_indexes_set(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                               u_long rhm010SessionInternalIndex_val)
{
    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionTable_indexes_set", "called\n"));

    if (MFD_SUCCESS !=
        rhm010SessionTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx,
                                               rhm010SessionInternalIndex_val))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if (0 != rhm010SessionTable_index_to_oid(&rowreq_ctx->oid_idx,
                                             &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
}                               /* rhm010SessionTable_indexes_set */


/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionVhostRef
 * rhm010SessionVhostRef is subid 1 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.1
 * Description:
Session vhostRef
                     Additional info ( nodeType:property, references:Vhost, index:y, parentRef:y )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is ObjId (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the rhm010SessionVhostRef data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionVhostRef_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param rhm010SessionVhostRef_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by rhm010SessionVhostRef.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*rhm010SessionVhostRef_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update rhm010SessionVhostRef_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
rhm010SessionVhostRef_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                          char **rhm010SessionVhostRef_val_ptr_ptr,
                          size_t *rhm010SessionVhostRef_val_ptr_len_ptr)
{
   /** we should have a non-NULL pointer and enough storage */
    netsnmp_assert((NULL != rhm010SessionVhostRef_val_ptr_ptr)
                   && (NULL != *rhm010SessionVhostRef_val_ptr_ptr));
    netsnmp_assert(NULL != rhm010SessionVhostRef_val_ptr_len_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionVhostRef_get",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionVhostRef data.
     * copy (* rhm010SessionVhostRef_val_ptr_ptr ) data and (* rhm010SessionVhostRef_val_ptr_len_ptr ) from rowreq_ctx->data
     */
    /*
     * make sure there is enough space for rhm010SessionVhostRef data
     */
    if ((NULL == (*rhm010SessionVhostRef_val_ptr_ptr)) ||
        ((*rhm010SessionVhostRef_val_ptr_len_ptr) <
         (rowreq_ctx->data.rhm010SessionVhostRef_len *
          sizeof(rowreq_ctx->data.rhm010SessionVhostRef[0])))) {
        /*
         * allocate space for rhm010SessionVhostRef data
         */
        (*rhm010SessionVhostRef_val_ptr_ptr) =
            malloc(rowreq_ctx->data.rhm010SessionVhostRef_len *
                   sizeof(rowreq_ctx->data.rhm010SessionVhostRef[0]));
        if (NULL == (*rhm010SessionVhostRef_val_ptr_ptr)) {
            snmp_log(LOG_ERR,
                     "could not allocate memory (rowreq_ctx->data.rhm010SessionVhostRef)\n");
            return MFD_ERROR;
        }
    }
    (*rhm010SessionVhostRef_val_ptr_len_ptr) =
        rowreq_ctx->data.rhm010SessionVhostRef_len *
        sizeof(rowreq_ctx->data.rhm010SessionVhostRef[0]);
    memcpy((*rhm010SessionVhostRef_val_ptr_ptr),
           rowreq_ctx->data.rhm010SessionVhostRef,
           rowreq_ctx->data.rhm010SessionVhostRef_len *
           sizeof(rowreq_ctx->data.rhm010SessionVhostRef[0]));

    return MFD_SUCCESS;
}                               /* rhm010SessionVhostRef_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionName
 * rhm010SessionName is subid 2 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadWrite.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.2
 * Description:
Session name
                     Additional info ( nodeType:property, index:y )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   1
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is Sstr (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the rhm010SessionName data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionName_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param rhm010SessionName_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by rhm010SessionName.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*rhm010SessionName_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update rhm010SessionName_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
rhm010SessionName_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                      char **rhm010SessionName_val_ptr_ptr,
                      size_t *rhm010SessionName_val_ptr_len_ptr)
{
   /** we should have a non-NULL pointer and enough storage */
    netsnmp_assert((NULL != rhm010SessionName_val_ptr_ptr)
                   && (NULL != *rhm010SessionName_val_ptr_ptr));
    netsnmp_assert(NULL != rhm010SessionName_val_ptr_len_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionName_get",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionName data.
     * copy (* rhm010SessionName_val_ptr_ptr ) data and (* rhm010SessionName_val_ptr_len_ptr ) from rowreq_ctx->data
     */
    /*
     * make sure there is enough space for rhm010SessionName data
     */
    if ((NULL == (*rhm010SessionName_val_ptr_ptr)) ||
        ((*rhm010SessionName_val_ptr_len_ptr) <
         (rowreq_ctx->data.rhm010SessionName_len *
          sizeof(rowreq_ctx->data.rhm010SessionName[0])))) {
        /*
         * allocate space for rhm010SessionName data
         */
        (*rhm010SessionName_val_ptr_ptr) =
            malloc(rowreq_ctx->data.rhm010SessionName_len *
                   sizeof(rowreq_ctx->data.rhm010SessionName[0]));
        if (NULL == (*rhm010SessionName_val_ptr_ptr)) {
            snmp_log(LOG_ERR,
                     "could not allocate memory (rowreq_ctx->data.rhm010SessionName)\n");
            return MFD_ERROR;
        }
    }
    (*rhm010SessionName_val_ptr_len_ptr) =
        rowreq_ctx->data.rhm010SessionName_len *
        sizeof(rowreq_ctx->data.rhm010SessionName[0]);
    memcpy((*rhm010SessionName_val_ptr_ptr),
           rowreq_ctx->data.rhm010SessionName,
           rowreq_ctx->data.rhm010SessionName_len *
           sizeof(rowreq_ctx->data.rhm010SessionName[0]));

    return MFD_SUCCESS;
}                               /* rhm010SessionName_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionChannelId
 * rhm010SessionChannelId is subid 3 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.3
 * Description:
Session channelId
                     Additional info ( nodeType:property )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   1
 *   settable   0
 *   hint: d
 *
 *
 * Its syntax is Uint16 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the rhm010SessionChannelId data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionChannelId_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionChannelId_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                           long *rhm010SessionChannelId_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionChannelId_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionChannelId_get",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionChannelId data.
     * copy (* rhm010SessionChannelId_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionChannelId_val_ptr) =
        rowreq_ctx->data.rhm010SessionChannelId;

    return MFD_SUCCESS;
}                               /* rhm010SessionChannelId_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionConnectionRef
 * rhm010SessionConnectionRef is subid 4 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.4
 * Description:
Session connectionRef
                     Additional info ( nodeType:property, references:Connection )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is ObjId (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the rhm010SessionConnectionRef data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionConnectionRef_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param rhm010SessionConnectionRef_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by rhm010SessionConnectionRef.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*rhm010SessionConnectionRef_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update rhm010SessionConnectionRef_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
rhm010SessionConnectionRef_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                               char
                               **rhm010SessionConnectionRef_val_ptr_ptr,
                               size_t
                               *rhm010SessionConnectionRef_val_ptr_len_ptr)
{
   /** we should have a non-NULL pointer and enough storage */
    netsnmp_assert((NULL != rhm010SessionConnectionRef_val_ptr_ptr)
                   && (NULL != *rhm010SessionConnectionRef_val_ptr_ptr));
    netsnmp_assert(NULL != rhm010SessionConnectionRef_val_ptr_len_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionConnectionRef_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionConnectionRef data.
     * copy (* rhm010SessionConnectionRef_val_ptr_ptr ) data and (* rhm010SessionConnectionRef_val_ptr_len_ptr ) from rowreq_ctx->data
     */
    /*
     * make sure there is enough space for rhm010SessionConnectionRef data
     */
    if ((NULL == (*rhm010SessionConnectionRef_val_ptr_ptr)) ||
        ((*rhm010SessionConnectionRef_val_ptr_len_ptr) <
         (rowreq_ctx->data.rhm010SessionConnectionRef_len *
          sizeof(rowreq_ctx->data.rhm010SessionConnectionRef[0])))) {
        /*
         * allocate space for rhm010SessionConnectionRef data
         */
        (*rhm010SessionConnectionRef_val_ptr_ptr) =
            malloc(rowreq_ctx->data.rhm010SessionConnectionRef_len *
                   sizeof(rowreq_ctx->data.rhm010SessionConnectionRef[0]));
        if (NULL == (*rhm010SessionConnectionRef_val_ptr_ptr)) {
            snmp_log(LOG_ERR,
                     "could not allocate memory (rowreq_ctx->data.rhm010SessionConnectionRef)\n");
            return MFD_ERROR;
        }
    }
    (*rhm010SessionConnectionRef_val_ptr_len_ptr) =
        rowreq_ctx->data.rhm010SessionConnectionRef_len *
        sizeof(rowreq_ctx->data.rhm010SessionConnectionRef[0]);
    memcpy((*rhm010SessionConnectionRef_val_ptr_ptr),
           rowreq_ctx->data.rhm010SessionConnectionRef,
           rowreq_ctx->data.rhm010SessionConnectionRef_len *
           sizeof(rowreq_ctx->data.rhm010SessionConnectionRef[0]));

    return MFD_SUCCESS;
}                               /* rhm010SessionConnectionRef_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionDetachedLifespan
 * rhm010SessionDetachedLifespan is subid 5 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.5
 * Description:
Session detachedLifespan
                     Additional info ( nodeType:property )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the rhm010SessionDetachedLifespan data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionDetachedLifespan_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionDetachedLifespan_get(rhm010SessionTable_rowreq_ctx *
                                  rowreq_ctx,
                                  u_long *
                                  rhm010SessionDetachedLifespan_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionDetachedLifespan_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionDetachedLifespan_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionDetachedLifespan data.
     * copy (* rhm010SessionDetachedLifespan_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionDetachedLifespan_val_ptr) =
        rowreq_ctx->data.rhm010SessionDetachedLifespan;

    return MFD_SUCCESS;
}                               /* rhm010SessionDetachedLifespan_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionAttached
 * rhm010SessionAttached is subid 6 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.6
 * Description:
Session attached
                     Additional info ( nodeType:property )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  1      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 * Enum range: 2/8. Values:  true(1), false(2)
 *
 * Its syntax is TruthValue (based on perltype INTEGER)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (u_long)
 */
/**
 * Extract the current value of the rhm010SessionAttached data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionAttached_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionAttached_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                          u_long * rhm010SessionAttached_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionAttached_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionAttached_get",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionAttached data.
     * copy (* rhm010SessionAttached_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionAttached_val_ptr) =
        rowreq_ctx->data.rhm010SessionAttached;

    return MFD_SUCCESS;
}                               /* rhm010SessionAttached_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionExpireTime
 * rhm010SessionExpireTime is subid 7 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.7
 * Description:
Session expireTime
                     Additional info ( nodeType:property, optional:y )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is TICKS (based on perltype TICKS)
 * The net-snmp type is ASN_TIMETICKS. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the rhm010SessionExpireTime data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionExpireTime_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionExpireTime_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                            u_long * rhm010SessionExpireTime_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionExpireTime_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionExpireTime_get",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionExpireTime data.
     * copy (* rhm010SessionExpireTime_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionExpireTime_val_ptr) =
        rowreq_ctx->data.rhm010SessionExpireTime;

    return MFD_SUCCESS;
}                               /* rhm010SessionExpireTime_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionMaxClientRate
 * rhm010SessionMaxClientRate is subid 8 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.8
 * Description:
Session maxClientRate
                     Additional info ( nodeType:property, optional:y )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is UNSIGNED32 (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the rhm010SessionMaxClientRate data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionMaxClientRate_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionMaxClientRate_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                               u_long * rhm010SessionMaxClientRate_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionMaxClientRate_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionMaxClientRate_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionMaxClientRate data.
     * copy (* rhm010SessionMaxClientRate_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionMaxClientRate_val_ptr) =
        rowreq_ctx->data.rhm010SessionMaxClientRate;

    return MFD_SUCCESS;
}                               /* rhm010SessionMaxClientRate_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionFramesOutstanding
 * rhm010SessionFramesOutstanding is subid 9 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.9
 * Description:
Session framesOutstanding
                     Additional info ( nodeType:statistic )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the rhm010SessionFramesOutstanding data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionFramesOutstanding_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionFramesOutstanding_get(rhm010SessionTable_rowreq_ctx *
                                   rowreq_ctx,
                                   u_long *
                                   rhm010SessionFramesOutstanding_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionFramesOutstanding_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionFramesOutstanding_get", "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionFramesOutstanding data.
     * copy (* rhm010SessionFramesOutstanding_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionFramesOutstanding_val_ptr) =
        rowreq_ctx->data.rhm010SessionFramesOutstanding;

    return MFD_SUCCESS;
}                               /* rhm010SessionFramesOutstanding_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionTxnStarts
 * rhm010SessionTxnStarts is subid 10 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.10
 * Description:
Total transactions started 
                     Additional info ( nodeType:statistic )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * Extract the current value of the rhm010SessionTxnStarts data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionTxnStarts_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionTxnStarts_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                           U64 * rhm010SessionTxnStarts_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionTxnStarts_val_ptr);

    /*
     * TODO:231:o: |-> copy rhm010SessionTxnStarts data.
     * get (* rhm010SessionTxnStarts_val_ptr ).low and (* rhm010SessionTxnStarts_val_ptr ).high from rowreq_ctx->data
     */
    (*rhm010SessionTxnStarts_val_ptr).high =
        rowreq_ctx->data.rhm010SessionTxnStarts.high;
    (*rhm010SessionTxnStarts_val_ptr).low =
        rowreq_ctx->data.rhm010SessionTxnStarts.low;


    return MFD_SUCCESS;
}                               /* rhm010SessionTxnStarts_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionTxnCommits
 * rhm010SessionTxnCommits is subid 11 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.11
 * Description:
Total transactions committed
                     Additional info ( nodeType:statistic )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * Extract the current value of the rhm010SessionTxnCommits data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionTxnCommits_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionTxnCommits_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                            U64 * rhm010SessionTxnCommits_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionTxnCommits_val_ptr);

    /*
     * TODO:231:o: |-> copy rhm010SessionTxnCommits data.
     * get (* rhm010SessionTxnCommits_val_ptr ).low and (* rhm010SessionTxnCommits_val_ptr ).high from rowreq_ctx->data
     */
    (*rhm010SessionTxnCommits_val_ptr).high =
        rowreq_ctx->data.rhm010SessionTxnCommits.high;
    (*rhm010SessionTxnCommits_val_ptr).low =
        rowreq_ctx->data.rhm010SessionTxnCommits.low;


    return MFD_SUCCESS;
}                               /* rhm010SessionTxnCommits_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionTxnRejects
 * rhm010SessionTxnRejects is subid 12 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.12
 * Description:
Total transactions rejected
                     Additional info ( nodeType:statistic )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER64 (based on perltype COUNTER64)
 * The net-snmp type is ASN_COUNTER64. The C type decl is U64 (U64)
 */
/**
 * Extract the current value of the rhm010SessionTxnRejects data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionTxnRejects_val_ptr
 *        Pointer to storage for a U64 variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionTxnRejects_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                            U64 * rhm010SessionTxnRejects_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionTxnRejects_val_ptr);

    /*
     * TODO:231:o: |-> copy rhm010SessionTxnRejects data.
     * get (* rhm010SessionTxnRejects_val_ptr ).low and (* rhm010SessionTxnRejects_val_ptr ).high from rowreq_ctx->data
     */
    (*rhm010SessionTxnRejects_val_ptr).high =
        rowreq_ctx->data.rhm010SessionTxnRejects.high;
    (*rhm010SessionTxnRejects_val_ptr).low =
        rowreq_ctx->data.rhm010SessionTxnRejects.low;


    return MFD_SUCCESS;
}                               /* rhm010SessionTxnRejects_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionTxnCount
 * rhm010SessionTxnCount is subid 13 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.13
 * Description:
Current pending transactions
                     Additional info ( nodeType:statistic )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the rhm010SessionTxnCount data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionTxnCount_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionTxnCount_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                          u_long * rhm010SessionTxnCount_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionTxnCount_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionTxnCount_get",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionTxnCount data.
     * copy (* rhm010SessionTxnCount_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionTxnCount_val_ptr) =
        rowreq_ctx->data.rhm010SessionTxnCount;

    return MFD_SUCCESS;
}                               /* rhm010SessionTxnCount_get */

/*---------------------------------------------------------------------
 * MRG-MESSAGING-MIB::rhm010SessionEntry.rhm010SessionClientCredit
 * rhm010SessionClientCredit is subid 14 of rhm010SessionEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.4.1.2312.5672.1.1.13.1.1.14
 * Description:
Client message credit
                     Additional info ( nodeType:statistic )
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is COUNTER (based on perltype COUNTER)
 * The net-snmp type is ASN_COUNTER. The C type decl is u_long (u_long)
 */
/**
 * Extract the current value of the rhm010SessionClientCredit data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param rhm010SessionClientCredit_val_ptr
 *        Pointer to storage for a u_long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
rhm010SessionClientCredit_get(rhm010SessionTable_rowreq_ctx * rowreq_ctx,
                              u_long * rhm010SessionClientCredit_val_ptr)
{
   /** we should have a non-NULL pointer */
    netsnmp_assert(NULL != rhm010SessionClientCredit_val_ptr);


    DEBUGMSGTL(("verbose:rhm010SessionTable:rhm010SessionClientCredit_get",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:231:o: |-> Extract the current value of the rhm010SessionClientCredit data.
     * copy (* rhm010SessionClientCredit_val_ptr ) from rowreq_ctx->data
     */
    (*rhm010SessionClientCredit_val_ptr) =
        rowreq_ctx->data.rhm010SessionClientCredit;

    return MFD_SUCCESS;
}                               /* rhm010SessionClientCredit_get */



/** @} */
