/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
#ifndef RHM010VHOSTTABLE_H
#define RHM010VHOSTTABLE_H

#ifdef __cplusplus
extern          "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

    /*
     * other required module components 
     */
    /* *INDENT-OFF*  */
config_add_mib(MRG-MESSAGING-MIB)
config_require(MRG-MESSAGING-MIB/rhm010VhostTable/rhm010VhostTable_interface)
config_require(MRG-MESSAGING-MIB/rhm010VhostTable/rhm010VhostTable_data_access)
config_require(MRG-MESSAGING-MIB/rhm010VhostTable/rhm010VhostTable_data_get)
config_require(MRG-MESSAGING-MIB/rhm010VhostTable/rhm010VhostTable_data_set)
    /* *INDENT-ON*  */

    /*
     * OID and column number definitions for rhm010VhostTable 
     */
#include "rhm010VhostTable_oids.h"

    /*
     * enum definions 
     */
#include "../enums.h"

    /*
     *********************************************************************
     * function declarations
     */
    void            init_rhm010VhostTable(void);
    void            shutdown_rhm010VhostTable(void);

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rhm010VhostTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * MRG-MESSAGING-MIB::rhm010VhostTable is subid 1 of rhm010Vhosts.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.2312.5672.1.1.5.1, length: 12
     */
    /*
     *********************************************************************
     * When you register your mib, you get to provide a generic
     * pointer that will be passed back to you for most of the
     * functions calls.
     *
     * TODO:100:r: Review all context structures
     */
    /*
     * TODO:101:o: |-> Review rhm010VhostTable registration context.
     */
    typedef netsnmp_data_list rhm010VhostTable_registration;

/**********************************************************************/
    /*
     * TODO:110:r: |-> Review rhm010VhostTable data context structure.
     * This structure is used to represent the data for rhm010VhostTable.
     */
    /*
     * This structure contains storage for all the columns defined in the
     * rhm010VhostTable.
     */
    typedef struct rhm010VhostTable_data_s {

        /*
         * rhm010VhostBrokerRef(1)/ObjId/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
        char            rhm010VhostBrokerRef[255];
        size_t          rhm010VhostBrokerRef_len;       /* # of char elements, not bytes */

        /*
         * rhm010VhostName(2)/Sstr/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
         */
        char            rhm010VhostName[255];
        size_t          rhm010VhostName_len;    /* # of char elements, not bytes */

        /*
         * rhm010VhostFederationTag(3)/Sstr/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
        char            rhm010VhostFederationTag[255];
        size_t          rhm010VhostFederationTag_len;   /* # of char elements, not bytes */

    } rhm010VhostTable_data;


    /*
     *********************************************************************
     * TODO:115:o: |-> Review rhm010VhostTable undo context.
     * We're just going to use the same data structure for our
     * undo_context. If you want to do something more efficent,
     * define your typedef here.
     */
    typedef rhm010VhostTable_data rhm010VhostTable_undo_data;

    /*
     * TODO:120:r: |-> Review rhm010VhostTable mib index.
     * This structure is used to represent the index for rhm010VhostTable.
     */
    typedef struct rhm010VhostTable_mib_index_s {

        /*
         * rhm010VhostInternalIndex(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/r/d/h
         */
        u_long          rhm010VhostInternalIndex;


    } rhm010VhostTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review rhm010VhostTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
     */
#define MAX_rhm010VhostTable_IDX_LEN     1


    /*
     *********************************************************************
     * TODO:130:o: |-> Review rhm010VhostTable Row request (rowreq) context.
     * When your functions are called, you will be passed a
     * rhm010VhostTable_rowreq_ctx pointer.
     */
    typedef struct rhm010VhostTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
        netsnmp_index   oid_idx;
        oid             oid_tmp[MAX_rhm010VhostTable_IDX_LEN];

        rhm010VhostTable_mib_index tbl_idx;

        rhm010VhostTable_data data;
        rhm010VhostTable_undo_data *undo;
        unsigned int    column_set_flags;       /* flags for set columns */


        /*
         * flags per row. Currently, the first (lower) 8 bits are reserved
         * for the user. See mfd.h for other flags.
         */
        u_int           rowreq_flags;

        /*
         * TODO:131:o: |   |-> Add useful data to rhm010VhostTable rowreq context.
         */

        /*
         * storage for future expansion
         */
        netsnmp_data_list *rhm010VhostTable_data_list;

    } rhm010VhostTable_rowreq_ctx;

    typedef struct rhm010VhostTable_ref_rowreq_ctx_s {
        rhm010VhostTable_rowreq_ctx *rowreq_ctx;
    } rhm010VhostTable_ref_rowreq_ctx;

    /*
     *********************************************************************
     * function prototypes
     */
    int            
        rhm010VhostTable_pre_request(rhm010VhostTable_registration *
                                     user_context);
    int            
        rhm010VhostTable_post_request(rhm010VhostTable_registration *
                                      user_context, int rc);

    int            
        rhm010VhostTable_rowreq_ctx_init(rhm010VhostTable_rowreq_ctx *
                                         rowreq_ctx, void *user_init_ctx);
    void           
        rhm010VhostTable_rowreq_ctx_cleanup(rhm010VhostTable_rowreq_ctx *
                                            rowreq_ctx);

    int            
        rhm010VhostTable_check_dependencies(rhm010VhostTable_rowreq_ctx *
                                            rowreq_ctx);
    int             rhm010VhostTable_commit(rhm010VhostTable_rowreq_ctx *
                                            rowreq_ctx);

    rhm010VhostTable_rowreq_ctx
        *rhm010VhostTable_row_find_by_mib_index(rhm010VhostTable_mib_index
                                                * mib_idx);

    extern const oid rhm010VhostTable_oid[];
    extern const int rhm010VhostTable_oid_size;


#include "rhm010VhostTable_interface.h"
#include "rhm010VhostTable_data_access.h"
#include "rhm010VhostTable_data_get.h"
#include "rhm010VhostTable_data_set.h"

    /*
     * DUMMY markers, ignore
     *
     * TODO:099:x: *************************************************************
     * TODO:199:x: *************************************************************
     * TODO:299:x: *************************************************************
     * TODO:399:x: *************************************************************
     * TODO:499:x: *************************************************************
     */

#ifdef __cplusplus
}
#endif
#endif                          /* RHM010VHOSTTABLE_H */
/** @} */
