/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef qpid010VHOSTTABLE_OIDS_H
#define qpid010VHOSTTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table qpid010VhostTable 
     */
#define qpid010VHOSTTABLE_OID              1,3,6,1,4,1,18060,5672,1,1,5,1


#define COLUMN_qpid010VHOSTBROKERREF         1
#define COLUMN_qpid010VHOSTBROKERREF_FLAG    (0x1 << 0)

#define COLUMN_qpid010VHOSTNAME         2
#define COLUMN_qpid010VHOSTNAME_FLAG    (0x1 << 1)

#define COLUMN_qpid010VHOSTFEDERATIONTAG         3

#define COLUMN_qpid010VHOSTINTERNALINDEX         4


#define qpid010VHOSTTABLE_MIN_COL   COLUMN_qpid010VHOSTBROKERREF
#define qpid010VHOSTTABLE_MAX_COL   COLUMN_qpid010VHOSTFEDERATIONTAG


    /*
     * TODO:405:r: Review qpid010VHOSTTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define qpid010VHOSTTABLE_SETTABLE_COLS (COLUMN_qpid010VHOSTBROKERREF_FLAG | COLUMN_qpid010VHOSTNAME_FLAG)

#ifdef __cplusplus
}
#endif
#endif                          /* qpid010VHOSTTABLE_OIDS_H */
