/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef brokerVHOSTTABLE_OIDS_H
#define brokerVHOSTTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table brokerVhostTable 
     */
#define brokerVHOSTTABLE_OID              1,3,6,1,4,1,18060,5672,1,5,1


#define COLUMN_brokerVHOSTBROKERREF         1
#define COLUMN_brokerVHOSTBROKERREF_FLAG    (0x1 << 0)

#define COLUMN_brokerVHOSTNAME         2
#define COLUMN_brokerVHOSTNAME_FLAG    (0x1 << 1)

#define COLUMN_brokerVHOSTFEDERATIONTAG         3

#define COLUMN_brokerVHOSTINTERNALINDEX         4


#define brokerVHOSTTABLE_MIN_COL   COLUMN_brokerVHOSTBROKERREF
#define brokerVHOSTTABLE_MAX_COL   COLUMN_brokerVHOSTFEDERATIONTAG


    /*
     * TODO:405:r: Review brokerVHOSTTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define brokerVHOSTTABLE_SETTABLE_COLS (COLUMN_brokerVHOSTBROKERREF_FLAG | COLUMN_brokerVHOSTNAME_FLAG)

#ifdef __cplusplus
}
#endif
#endif                          /* brokerVHOSTTABLE_OIDS_H */
