/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef qpid010EVENTS_H
#define qpid010EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * function declarations 
 */
int				send_qpid010EvtClientConnect_trap(const char * rHost, const char * user);
int 			send_qpid010EvtClientConnectFail_trap(const char * rHost, const char * user, const char * reason);
int 			send_qpid010EvtClientDisconnect_trap(const char * rHost, const char * user);
int             send_qpid010EvtBrokerLinkUp_trap(const char *rHost);
int             send_qpid010EvtBrokerLinkDown_trap(const char *rHost);
int				send_qpid010EvtQueueDeclare_trap(const char *rHost, const char * user, const char * qName,
					int durable, int exclusive, int autoDelete, const char *altEx,
					const char *args, const char *disp);
int             send_qpid010EvtQueueDelete_trap(const char *rHost, const char * user, const char * qName);
int             send_qpid010EvtExchangeDeclare_trap(const char *rHost, const char * user, const char * exName,
					const char *exType, const char *altEx, int durable, int autoDelete,
					const char *args, const char *disp);
int             send_qpid010EvtExchangeDelete_trap(const char *rHost, const char * user, const char * exName);
int 			send_qpid010EvtBind_trap(const char *rHost, const char * user,
					const char *exName, const char *qName, const char * key, const char * args);
int             send_qpid010EvtUnbind_trap(const char *rHost, const char * user,
					const char *exName, const char *qName, const char * key);
int 			send_qpid010EvtSubscribe_trap(const char *rHost, const char * user, const char * qName,
					int exclusive, const char *dest, const char *args);
int				send_qpid010EvtUnsubscribe_trap(const char *rHost, const char * user, const char *dest);
int             send_qpid010EvtQueueThresholdExceeded_trap(const char *qName, uint64_t msgDepth, uint64_t byteDepth);
int             send_qpid010EvtAllow_trap(const char *user, const char *action, const char *objectType,
					const char *objectName, const char *args);
int             send_qpid010EvtDeny_trap(const char *user, const char *action, const char *objectType,
					const char *objectName, const char *args);
int             send_qpid010EvtFileLoaded_trap(const char *user);
int             send_qpid010EvtFileLoadFailed_trap(const char *user, const char *reason);

#ifdef __cplusplus
}
#endif

#endif                          /* qpid010EVENTS_H */
