/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef brokerBRIDGETABLE_INTERFACE_H
#define brokerBRIDGETABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "BridgeTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _brokerBridgeTable_initialize_interface
        (brokerBridgeTable_registration * user_ctx, u_long flags);
    void           
        _brokerBridgeTable_shutdown_interface
        (brokerBridgeTable_registration * user_ctx);

    brokerBridgeTable_registration
        *brokerBridgeTable_registration_get(void);

    brokerBridgeTable_registration
        *brokerBridgeTable_registration_set(brokerBridgeTable_registration
                                            * newreg);

    netsnmp_container *brokerBridgeTable_container_get(void);
    int             brokerBridgeTable_container_size(void);

    u_int           brokerBridgeTable_dirty_get(void);
    void            brokerBridgeTable_dirty_set(u_int status);

    brokerBridgeTable_rowreq_ctx
        *brokerBridgeTable_allocate_rowreq_ctx(void *);
    void           
        brokerBridgeTable_release_rowreq_ctx(brokerBridgeTable_rowreq_ctx *
                                             rowreq_ctx);

    int             brokerBridgeTable_index_to_oid(netsnmp_index * oid_idx,
                                                   brokerBridgeTable_mib_index
                                                   * mib_idx);
    int             brokerBridgeTable_index_from_oid(netsnmp_index *
                                                     oid_idx,
                                                     brokerBridgeTable_mib_index
                                                     * mib_idx);

    /*
     *********************************************************************
     * Persistent declarations
     */
    /*
     * persistence
     */
#define LINE_TERM_CHAR '$'

    void           
        brokerBridgeTable_container_init_persistence(netsnmp_container *
                                                     container);
    int            
        brokerBridgeTable_container_should_save
        (brokerBridgeTable_rowreq_ctx * rowreq_ctx);


    /*
     * access to certain internals. use with caution!
     */
    void            brokerBridgeTable_valid_columns_set(netsnmp_column_info
                                                        *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* brokerBRIDGETABLE_INTERFACE_H */
/** @} */
