/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 *
 * $Id:$
 */
#ifndef qpid010BINDINGTABLE_OIDS_H
#define qpid010BINDINGTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table qpid010BindingTable 
     */
#define qpid010BINDINGTABLE_OID              1,3,6,1,4,1,18060,15,1,1,8,1


#define COLUMN_qpid010BINDINGEXCHANGEREF         1
#define COLUMN_qpid010BINDINGEXCHANGEREF_FLAG    (0x1 << 0)

#define COLUMN_qpid010BINDINGQUEUEREF         2
#define COLUMN_qpid010BINDINGQUEUEREF_FLAG    (0x1 << 1)

#define COLUMN_qpid010BINDINGBINDINGKEY         3
#define COLUMN_qpid010BINDINGBINDINGKEY_FLAG    (0x1 << 2)

#define COLUMN_qpid010BINDINGARGUMENTS         4
#define COLUMN_qpid010BINDINGARGUMENTS_FLAG    (0x1 << 3)

#define COLUMN_qpid010BINDINGORIGIN         5

#define COLUMN_qpid010BINDINGMSGMATCHED         6

#define COLUMN_qpid010BINDINGINTERNALINDEX         7


#define qpid010BINDINGTABLE_MIN_COL   COLUMN_qpid010BINDINGEXCHANGEREF
#define qpid010BINDINGTABLE_MAX_COL   COLUMN_qpid010BINDINGMSGMATCHED


    /*
     * TODO:405:r: Review qpid010BINDINGTABLE_SETTABLE_COLS macro.
     * OR together all the writable cols.
     */
#define qpid010BINDINGTABLE_SETTABLE_COLS (COLUMN_qpid010BINDINGEXCHANGEREF_FLAG | COLUMN_qpid010BINDINGQUEUEREF_FLAG | COLUMN_qpid010BINDINGBINDINGKEY_FLAG | COLUMN_qpid010BINDINGARGUMENTS_FLAG)

#ifdef __cplusplus
}
#endif
#endif                          /* qpid010BINDINGTABLE_OIDS_H */
