/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $ 
 *
 * $Id:$
 */
#ifndef qpid010BINDINGTABLE_DATA_SET_H
#define qpid010BINDINGTABLE_DATA_SET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * SET function declarations
     */

    /*
     *********************************************************************
     * SET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table qpid010BindingTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * MRG-MESSAGING-MIB::qpid010BindingTable is subid 1 of qpid010Bindings.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.18060.5672.1.1.8.1, length: 12
     */


    int            
        qpid010BindingTable_undo_setup(qpid010BindingTable_rowreq_ctx *
                                      rowreq_ctx);
    int            
        qpid010BindingTable_undo_cleanup(qpid010BindingTable_rowreq_ctx *
                                        rowreq_ctx);
    int             qpid010BindingTable_undo(qpid010BindingTable_rowreq_ctx *
                                            rowreq_ctx);
    int             qpid010BindingTable_commit(qpid010BindingTable_rowreq_ctx
                                              * rowreq_ctx);
    int            
        qpid010BindingTable_undo_commit(qpid010BindingTable_rowreq_ctx *
                                       rowreq_ctx);


    int            
        qpid010BindingExchangeRef_check_value(qpid010BindingTable_rowreq_ctx
                                             * rowreq_ctx,
                                             char
                                             *qpid010BindingExchangeRef_val_ptr,
                                             size_t
                                             qpid010BindingExchangeRef_val_ptr_len);
    int            
        qpid010BindingExchangeRef_undo_setup(qpid010BindingTable_rowreq_ctx *
                                            rowreq_ctx);
    int            
        qpid010BindingExchangeRef_set(qpid010BindingTable_rowreq_ctx *
                                     rowreq_ctx,
                                     char
                                     *qpid010BindingExchangeRef_val_ptr,
                                     size_t
                                     qpid010BindingExchangeRef_val_ptr_len);
    int            
        qpid010BindingExchangeRef_undo(qpid010BindingTable_rowreq_ctx *
                                      rowreq_ctx);

    int            
        qpid010BindingQueueRef_check_value(qpid010BindingTable_rowreq_ctx *
                                          rowreq_ctx,
                                          char
                                          *qpid010BindingQueueRef_val_ptr,
                                          size_t
                                          qpid010BindingQueueRef_val_ptr_len);
    int            
        qpid010BindingQueueRef_undo_setup(qpid010BindingTable_rowreq_ctx *
                                         rowreq_ctx);
    int             qpid010BindingQueueRef_set(qpid010BindingTable_rowreq_ctx
                                              * rowreq_ctx,
                                              char
                                              *qpid010BindingQueueRef_val_ptr,
                                              size_t
                                              qpid010BindingQueueRef_val_ptr_len);
    int            
        qpid010BindingQueueRef_undo(qpid010BindingTable_rowreq_ctx *
                                   rowreq_ctx);

    int            
        qpid010BindingBindingKey_check_value(qpid010BindingTable_rowreq_ctx *
                                            rowreq_ctx,
                                            char
                                            *qpid010BindingBindingKey_val_ptr,
                                            size_t
                                            qpid010BindingBindingKey_val_ptr_len);
    int            
        qpid010BindingBindingKey_undo_setup(qpid010BindingTable_rowreq_ctx *
                                           rowreq_ctx);
    int            
        qpid010BindingBindingKey_set(qpid010BindingTable_rowreq_ctx *
                                    rowreq_ctx,
                                    char *qpid010BindingBindingKey_val_ptr,
                                    size_t
                                    qpid010BindingBindingKey_val_ptr_len);
    int            
        qpid010BindingBindingKey_undo(qpid010BindingTable_rowreq_ctx *
                                     rowreq_ctx);

    int            
        qpid010BindingArguments_check_value(qpid010BindingTable_rowreq_ctx *
                                           rowreq_ctx,
                                           char
                                           *qpid010BindingArguments_val_ptr,
                                           size_t
                                           qpid010BindingArguments_val_ptr_len);
    int            
        qpid010BindingArguments_undo_setup(qpid010BindingTable_rowreq_ctx *
                                          rowreq_ctx);
    int            
        qpid010BindingArguments_set(qpid010BindingTable_rowreq_ctx *
                                   rowreq_ctx,
                                   char *qpid010BindingArguments_val_ptr,
                                   size_t
                                   qpid010BindingArguments_val_ptr_len);
    int            
        qpid010BindingArguments_undo(qpid010BindingTable_rowreq_ctx *
                                    rowreq_ctx);

    int            
        qpid010BindingOrigin_check_value(qpid010BindingTable_rowreq_ctx *
                                        rowreq_ctx,
                                        char *qpid010BindingOrigin_val_ptr,
                                        size_t
                                        qpid010BindingOrigin_val_ptr_len);
    int            
        qpid010BindingOrigin_undo_setup(qpid010BindingTable_rowreq_ctx *
                                       rowreq_ctx);
    int             qpid010BindingOrigin_set(qpid010BindingTable_rowreq_ctx *
                                            rowreq_ctx,
                                            char
                                            *qpid010BindingOrigin_val_ptr,
                                            size_t
                                            qpid010BindingOrigin_val_ptr_len);
    int             qpid010BindingOrigin_undo(qpid010BindingTable_rowreq_ctx
                                             * rowreq_ctx);

    int            
        qpid010BindingMsgMatched_check_value(qpid010BindingTable_rowreq_ctx *
                                            rowreq_ctx,
                                            U64
                                            qpid010BindingMsgMatched_val);
    int            
        qpid010BindingMsgMatched_undo_setup(qpid010BindingTable_rowreq_ctx *
                                           rowreq_ctx);
    int            
        qpid010BindingMsgMatched_set(qpid010BindingTable_rowreq_ctx *
                                    rowreq_ctx,
                                    U64 qpid010BindingMsgMatched_val);
    int            
        qpid010BindingMsgMatched_undo(qpid010BindingTable_rowreq_ctx *
                                     rowreq_ctx);


    int            
        qpid010BindingTable_check_dependencies(qpid010BindingTable_rowreq_ctx
                                              * ctx);


#ifdef __cplusplus
}
#endif
#endif                          /* qpid010BINDINGTABLE_DATA_SET_H */
