/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef qpid010BINDINGTABLE_INTERFACE_H
#define qpid010BINDINGTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "BindingTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _qpid010BindingTable_initialize_interface
        (qpid010BindingTable_registration * user_ctx, u_long flags);
    void           
        _qpid010BindingTable_shutdown_interface
        (qpid010BindingTable_registration * user_ctx);

    qpid010BindingTable_registration
        *qpid010BindingTable_registration_get(void);

    qpid010BindingTable_registration
        *qpid010BindingTable_registration_set
        (qpid010BindingTable_registration * newreg);

    netsnmp_container *qpid010BindingTable_container_get(void);
    int             qpid010BindingTable_container_size(void);

    u_int           qpid010BindingTable_dirty_get(void);
    void            qpid010BindingTable_dirty_set(u_int status);

    qpid010BindingTable_rowreq_ctx
        *qpid010BindingTable_allocate_rowreq_ctx(void *);
    void           
        qpid010BindingTable_release_rowreq_ctx(qpid010BindingTable_rowreq_ctx
                                              * rowreq_ctx);

    int             qpid010BindingTable_index_to_oid(netsnmp_index *
                                                    oid_idx,
                                                    qpid010BindingTable_mib_index
                                                    * mib_idx);
    int             qpid010BindingTable_index_from_oid(netsnmp_index *
                                                      oid_idx,
                                                      qpid010BindingTable_mib_index
                                                      * mib_idx);

    /*
     *********************************************************************
     * Persistent declarations
     */
    /*
     * persistence
     */
#define LINE_TERM_CHAR '$'

    void           
        qpid010BindingTable_container_init_persistence(netsnmp_container *
                                                      container);
    int            
        qpid010BindingTable_container_should_save
        (qpid010BindingTable_rowreq_ctx * rowreq_ctx);


    /*
     * access to certain internals. use with caution!
     */
    void           
        qpid010BindingTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* qpid010BINDINGTABLE_INTERFACE_H */
/** @} */
