/*
 * Note: this file originally auto-generated by mib2c using
 *       version $ of $
 *
 * $Id:$
 *
 * @file rhm010BindingTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef RHM010BINDINGTABLE_DATA_GET_H
#define RHM010BINDINGTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table rhm010BindingTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * MRG-MESSAGING-MIB::rhm010BindingTable is subid 1 of rhm010Bindings.
     * Its status is Current.
     * OID: .1.3.6.1.4.1.2312.5672.1.1.8.1, length: 12
     */
    /*
     * indexes
     */

    int            
        rhm010BindingExchangeRef_get(rhm010BindingTable_rowreq_ctx *
                                     rowreq_ctx,
                                     char
                                     **rhm010BindingExchangeRef_val_ptr_ptr,
                                     size_t
                                     *rhm010BindingExchangeRef_val_ptr_len_ptr);
    int             rhm010BindingQueueRef_get(rhm010BindingTable_rowreq_ctx
                                              * rowreq_ctx,
                                              char
                                              **rhm010BindingQueueRef_val_ptr_ptr,
                                              size_t
                                              *rhm010BindingQueueRef_val_ptr_len_ptr);
    int            
        rhm010BindingBindingKey_get(rhm010BindingTable_rowreq_ctx *
                                    rowreq_ctx,
                                    char
                                    **rhm010BindingBindingKey_val_ptr_ptr,
                                    size_t
                                    *rhm010BindingBindingKey_val_ptr_len_ptr);
    int            
        rhm010BindingArguments_get(rhm010BindingTable_rowreq_ctx *
                                   rowreq_ctx,
                                   char
                                   **rhm010BindingArguments_val_ptr_ptr,
                                   size_t
                                   *rhm010BindingArguments_val_ptr_len_ptr);
    int             rhm010BindingOrigin_get(rhm010BindingTable_rowreq_ctx *
                                            rowreq_ctx,
                                            char
                                            **rhm010BindingOrigin_val_ptr_ptr,
                                            size_t
                                            *rhm010BindingOrigin_val_ptr_len_ptr);
    int            
        rhm010BindingMsgMatched_get(rhm010BindingTable_rowreq_ctx *
                                    rowreq_ctx,
                                    U64 * rhm010BindingMsgMatched_val_ptr);


    int            
        rhm010BindingTable_indexes_set_tbl_idx(rhm010BindingTable_mib_index
                                               * tbl_idx,
                                               u_long
                                               rhm010BindingInternalIndex_val);
    int            
        rhm010BindingTable_indexes_set(rhm010BindingTable_rowreq_ctx *
                                       rowreq_ctx,
                                       u_long
                                       rhm010BindingInternalIndex_val);




#ifdef __cplusplus
}
#endif
#endif                          /* RHM010BINDINGTABLE_DATA_GET_H */
/** @} */
